

#+TITLE: Emacs initialization

* Early initialization
:PROPERTIES:
:header-args: :tangle early-init.el
:END:

Emacs 27+ loads =early-init.el= before =package.el= is initialized and
before the GUI is drawn. Straight.el replaces =package.el= as the
package manager, so =package.el= is disabled here to prevent it from
loading packages at startup (which otherwise triggers a warning from
straight.el about duplicate package versions).

#+BEGIN_SRC emacs-lisp
  ;;; -*- lexical-binding: t -*-
  (setq package-enable-at-startup nil)
#+END_SRC

* Emacs Initialization
:PROPERTIES:
:header-args: :tangle init.el
:END:

This document describes how Emacs is initialized.
** Run local pre-initialization

Run machine dependant initialization file before running the common
setup. This file (=~/.emacs.d/local-pre-init.el=) should contain configuration
that varies between machines, such as:

- Proxy settings
- AI/LLM backend configuration (Bedrock vs Claude API, Ollama settings)
- Machine-specific environment variables
- Custom paths or hostnames

#+BEGIN_SRC emacs-lisp
  ;;; -*- lexical-binding: t -*-
  (setq local-pre-init-file "~/.emacs.d/local-pre-init.el")
  (if (file-exists-p local-pre-init-file)
  (load local-pre-init-file)
  )
#+END_SRC

*** Example: Proxy Setup

Following snippet can be used to set up proxy. It tries to ping the
host and if it succeeds within one second, it sets up environment
variables. Package managers will use these when cloning repositories.

#+BEGIN_EXAMPLE emacs-lisp
;; In local-pre-init.el:
(if (= 0 (call-process "ping" nil nil nil "-W" "1" "-c" "1" "1.2.3.4"))
    (progn
      (setenv "http_proxy" "http://1.2.3.4:8080")
      (setenv "https_proxy" "http://1.2.3.4:8080")))
#+END_EXAMPLE

*** Example: AI Backend Configuration

See the "AI tool setup" section below for detailed examples of how to
configure different LLM backends (Bedrock, Claude API, Ollama) in
=local-pre-init.el= for work vs personal machines.

** Straight packet manager

#+BEGIN_SRC emacs-lisp
(defvar bootstrap-version)
(let ((bootstrap-file
       (expand-file-name
        "straight/repos/straight.el/bootstrap.el"
        (or (bound-and-true-p straight-base-dir)
            user-emacs-directory)))
      (bootstrap-version 7))
  (unless (file-exists-p bootstrap-file)
    (with-current-buffer
        (url-retrieve-synchronously
         "https://raw.githubusercontent.com/radian-software/straight.el/develop/install.el"
         'silent 'inhibit-cookies)
      (goto-char (point-max))
      (eval-print-last-sexp)))
  (load bootstrap-file nil 'nomessage))
#+END_SRC

Install =use-package= via straight and make =:straight t= the implicit
default for every =use-package= form. Without this, a bare
=use-package= falls back to =package.el= (=:straight t=), which loads
=package.el= alongside straight and produces the "package.el was
loaded when straight.el was already loaded" warning.

#+BEGIN_SRC emacs-lisp
  (straight-use-package 'use-package)
  (setq straight-use-package-by-default t)
#+END_SRC

** Appearance
*** All the icons
#+BEGIN_SRC emacs-lisp
  (use-package all-the-icons
  :straight t)
#+END_SRC

*** Nerd icons

Nerd icons are used by doom-themes treemacs theme and doom-modeline.
Fonts are installed automatically on first launch if missing.

#+BEGIN_SRC emacs-lisp
  (use-package nerd-icons
    :straight t
    :config
    (let ((font-dest (concat (or (getenv "XDG_DATA_HOME")
                                 (concat (getenv "HOME") "/.local/share"))
                             "/fonts/"
                             nerd-icons-fonts-subdirectory)))
      (unless (cl-every (lambda (font)
                          (file-exists-p (expand-file-name font font-dest)))
                        nerd-icons-font-names)
        (nerd-icons-install-fonts t))))
#+END_SRC
*** Minimalistic user interface

Emacs shows startup screen. It gets anoying after a while, so they
need to be turned off.

#+BEGIN_SRC emacs-lisp 
  (setq inhibit-startup-message t)
  (setq inhibit-splash-screen t)
#+END_SRC

After getting used to the keyboard interface the menus and such just
takes valuable screen space. So mouse interface is turned off.
This is done early in the initialization to prevent momentary display.

#+BEGIN_SRC emacs-lisp 
(if (fboundp 'menu-bar-mode) (menu-bar-mode -1))
(if (fboundp 'tool-bar-mode) (tool-bar-mode -1))
(if (fboundp 'scroll-bar-mode) (scroll-bar-mode -1))
#+END_SRC

*** Fonts

Editing a lot of text using fixed width font is not optimum situation. After a while of googling 
I found a way to use variable length fonts (see [[https://yoo2080.wordpress.com/2013/05/30/monospace-font-in-tables-and-source-code-blocks-in-org-mode-proportional-font-in-other-parts/][the blog of Jisan Yoo]]).

First we hook variable-pitch-mode
#+BEGIN_SRC emacs-lisp 
  (add-hook 'text-mode-hook 'variable-pitch-mode)
#+END_SRC

The problem is that I don't want code and tables to be variable width inside
Org mode document. This can be archived by altering some faces
used by the Org mode.

#+BEGIN_SRC emacs-lisp :tangle no
  (defun my-adjoin-to-list-or-symbol (element list-or-symbol)
    (let ((list (if (not (listp list-or-symbol))
                    (list list-or-symbol)
                  list-or-symbol)))
      (require 'cl-lib)
      (cl-adjoin element list)))

    (mapc
      (lambda (face)
        (set-face-attribute
         face nil
         :inherit
         (my-adjoin-to-list-or-symbol
          'fixed-pitch
          (face-attribute face :inherit))))
      (list 'org-code 'org-block 'org-table 'org-meta-line))
#+END_SRC

*** Doom Themes

#+BEGIN_SRC emacs-lisp
  (use-package doom-themes
    :straight t
    :straight t
    :config
    ;; Global settings (defaults)
    (setq doom-themes-enable-bold t    ; if nil, bold is universally disabled
          doom-themes-enable-italic t) ; if nil, italics is universally disabled
    (load-theme 'doom-acario-dark t)

    ;; Enable flashing mode-line on errors
    (doom-themes-visual-bell-config)
    ;; Enable custom neotree theme (nerd-icons must be installed!)
    (doom-themes-neotree-config)
    ;; Corrects (and improves) org-mode's native fontification.
    (doom-themes-org-config))  
#+END_SRC

#+BEGIN_SRC emacs-lisp
  (use-package doom-modeline
  :straight t
  :straight t
  :init (doom-modeline-mode 1))
  
 #+END_SRC


  Of course we can choose what kind of faces ~variable-pitch~ and ~fixed-pitch~ are.
 #+BEGIN_SRC emacs-lisp :tangle no
  (set-face-attribute 'variable-pitch nil :height 1.3 :family "FiraCode Nerd Font")
    (set-face-attribute 'variable-pitch nil :height 1.3 :family "Calibri")
    (set-face-attribute 'fixed-pitch nil :height 0.8 :family "DejaVu Sans Mono")
#+END_SRC

While we are at it we could make Org-mode look a little better in general.
#+BEGIN_SRC emacs-lisp :tangle no
(require 'org-bullets)
(add-hook 'org-mode-hook 'org-indent-mode)
(add-hook 'org-mode-hook (lambda () (org-bullets-mode 1)))
(setq org-hide-leading-stars t)
(setq line-spacing 0.25)
(set-face-attribute 'org-tag nil :weight 'normal :height 0.8)
(set-face-attribute 'org-todo nil :weight 'normal :height 150)
(set-face-attribute 'org-priority nil :weight 'normal :height 100)
(set-face-attribute 'org-todo nil :weight 'normal :height 100)
(set-face-attribute 'org-done nil :weight 'normal :height 100)
(set-face-attribute 'org-special-keyword nil :height 90)
(set-face-attribute 'org-level-1 nil :height 1.3)
(set-face-attribute 'org-level-2 nil :height 1.2)
(set-face-attribute 'org-level-3 nil :height 1.1)
#+END_SRC

*** Gaps between windows

Small gaps between windows make it easier to see where one window
ends and the next begins.

#+BEGIN_SRC emacs-lisp
  (setq window-divider-default-right-width 4
        window-divider-default-bottom-width 4)
  (set-face-foreground 'window-divider "#2E3044")
  (window-divider-mode 1)
#+END_SRC

*** Minibuffer to center of the screen

With wide screen it is a bit complicated to see lower left of the screen. This moves minibuffer to center.

#+BEGIN_SRC emacs-lisp
    (use-package vertico-posframe
      :straight t
      :after vertico
      :init
      (vertico-posframe-mode 1)
      (setq vertico-posframe-poshandler 'posframe-poshandler-frame-top-center)
      )
  #+END_SRC

** Treemacs

The highlight line face is brightened so it is visible against the
dark background of doom-acario-dark.

#+BEGIN_SRC emacs-lisp
  (use-package treemacs
    :straight t
    :bind
    ("C-x t t" . treemacs-select-window)
    :config
    (setq treemacs-width 30)
    (set-face-attribute 'treemacs-hl-line-face nil
                        :background "#2a2a3e"
                        :extend t))
#+END_SRC

Nerd-icons theme for treemacs replaces the doom-themes treemacs
integration which depends on all-the-icons fonts.

#+BEGIN_SRC emacs-lisp
  (use-package treemacs-nerd-icons
    :straight t
    :after treemacs
    :config
    (treemacs-load-theme "nerd-icons"))
  #+END_SRC
** Docker

#+BEGIN_SRC emacs-lisp
(use-package docker
  :straight t
  :straight t
  :bind ("C-c d" . docker))
  #+END_SRC
  
** Exec path

At least in MacOS there is problems of ~exec-path~ being insufficient.
The main hedeach this causes is that gpg is not found and encrypted
files can not be opened or saved.

Following code will extract exec-path from ~PATH~ variable.

#+BEGIN_SRC emacs-lisp 
(let ((elements (split-string (getenv "PATH") ":")))
  (dolist (e elements)
    (add-to-list 'exec-path e)))
#+END_SRC

In some cases ~bin~ directory in home directory is missing in the ~exec-path~. Same thing goes to the
~/usr/local/bin~. These are often used in my machines.

#+BEGIN_SRC emacs-lisp 
(add-to-list 'exec-path "~/bin")
(add-to-list 'exec-path "/usr/local/bin")
#+END_SRC

** Lisp files

Additional lisp code is located in own directory. These can be loaded
later using ~require~ function for example.

#+BEGIN_SRC emacs-lisp 
(add-to-list 'load-path "~/.emacs.d/lisp/")
#+END_SRC

** Using GPG-Agent in MacOS

MacOS is a "funny" thing. There is a different environment for shell and
different for applications. This will set the SSH agent socket for Emacs.

#+BEGIN_SRC emacs-lisp 
  (when (eq system-type 'darwin)
  (setenv "SSH_AUTH_SOCK" (concat (getenv "HOME") "/.gnupg/S.gpg-agent.ssh")))
#+END_SRC

** Tabs

Do not indent with tabs by default.

#+BEGIN_SRC emacs-lisp 
(setq-default indent-tabs-mode nil)
#+END_SRC

But if you do use tab its width is two.
#+BEGIN_SRC emacs-lisp 
(setq-default tab-width 2)
#+END_SRC

** No transient mark by default

Following disables [[https://www.emacswiki.org/emacs/TransientMarkMode][transient mark mode]]. This means that text is not selected by
default like in "normal" editors.  This allows more convient text editing while
it requires some practice.

#+BEGIN_SRC emacs-lisp 
(transient-mark-mode 0)
#+END_SRC

** Allow narrowing buffer

After over year of practice I am begin to think that can start to lear some
[[https://www.emacswiki.org/emacs/Narrowing][narrowing]]. It is disabled by default and needs to be enabled.

#+BEGIN_SRC emacs-lisp 
(put 'narrow-to-region 'disabled nil)
#+END_SRC

** Backups

#+BEGIN_SRC emacs-lisp 
(setq backup-directory-alist '(("." . "~/.emacs.d/backups")))
(setq
  delete-old-versions t
  kept-new-versions 6
  kept-old-versions 2
  version-control t
  backup-by-copying t
)
#+END_SRC

** Browser

#+BEGIN_SRC emacs-lisp 
  (when (eq system-type 'darwin)
     (setq browse-url-browser-function 'browse-url-default-macosx-browser))
#+END_SRC

** Org-mode

https://emacs.cafe/emacs/orgmode/gtd/2017/06/30/orgmode-gtd.html

Set up agenda functionality. Files are located under org-directory
under home.

#+BEGIN_SRC emacs-lisp 
(setq org-directory "~/org")
(setq org-agenda-files (concat org-directory "/agenda"))
(setq org-default-notes-file (concat org-directory "/refile.org.gpg"))
#+END_SRC


Set up archive file that is encrypted. By default entries would be archive
to files postfixed by ~_archive~. This file is not encrypted and that could
be a problem.

#+BEGIN_SRC emacs-lisp 
(setq org-archive-location (concat org-directory "/archive.org.gpg::* From %s"))
#+END_SRC


Setup default keys (see [[http://orgmode.org/org.html#Activation][Org mode activation]]). There has not been any
reason to change them yet.
#+BEGIN_SRC emacs-lisp 
  (global-set-key "\C-cl" 'org-store-link)
  (global-set-key "\C-ca" 'org-agenda)
  (global-set-key "\C-cc" 'org-capture)
  (global-set-key "\C-cb" 'org-iswitchb)
#+END_SRC



Active babel languages.
#+BEGIN_SRC emacs-lisp 
(org-babel-do-load-languages
 'org-babel-load-languages
 '(
   (makefile . t)
   (shell . t)
   (js . t)
   (plantuml . t)
   (emacs-lisp  . t)
   (ditaa . t)
   ))
#+END_SRC

*** State changes and logging 

Following will add GTD type of state for the tasks and provide logging.

#+BEGIN_SRC emacs-lisp 
(setq org-log-into-drawer t)
(setq org-todo-keywords '((sequence  "TODO(t!)" "WAIT(w@/!)" "|" "DONE(d!)" "CANCELLED(c@)")))
#+END_SRC

Log looks something like this under the task header line.
#+BEGIN_EXAMPLE
:LOGBOOK:
- State "WAIT"       from "DONE"       [2016-02-22 Mon 16:03]
- State "WAIT"       from "TODO"       [2016-02-22 Mon 16:03]
:END:
#+END_EXAMPLE
apture templates

#+BEGIN_SRC emacs-lisp 
  (setq org-capture-templates
        '(
          ("t" "Task" entry (file "")
            "* TODO %?\n:LOGBOOK:\n- Created %U\n:END:\n%i\n"
           :empty-lines 1)

          ("n" "Note" entry (file "")
           "* %? :muistiinpano:\n:LOGBOOK:\n- Created %U\n:END:\n%i\n"
           :empty-lines 1)

          ("m" "Meeting" entry (file "")
           "* %u %? :tapaminen:\n:LOGBOOK:\n- Created %U\n:END:\n"
           :clock-in t :clock-resume t  :empty-lines 1)

          ("c" "Phone call" entry (file "")
           "* %U %? :puhelu:\n:LOGBOOK:\n- Created %U\n:END:\n"
           :clock-in t :clock-resume t  :empty-lines 1)

          ("j" "Journal" entry (file+datetree "~/org/diary.org.gpg")
           "* %U\n\n%?")

          ("e" "Event" entry (file "")
           "* %? :tapahtuma:\n <%(org-read-date)> \n"
           )))

#+END_SRC


Following enables org-protocol handling. This means that url-like ~org-protocol://capture:/p/<url>/<title>/selection>~
are handled by the org mode capture.

#+begin_src emacs-lisp  
(require 'org-protocol)
#+end_src

Unfinished improvements for GTD.
#+BEGIN_SRC emacs-lisp
      (setq org-agenda-custom-commands
                  '(
                    ("A" "All tasks (for export)" todo ""
                    (
                    (org-agenda-overriding-header "Export")
                    (org-agenda-with-colors nil)
                    ) ("~/org/exported-lists/all.org"))
                    ("Gw" "Agenda työ"
                     (
                       (agenda "" ((org-agenda-span 1)             ; daily agenda
                          (org-deadline-warning-days 7)            ; 7 day advanced warning for deadlines
                          (org-agenda-todo-keyword-format "")
                          (org-agenda-scheduled-leaders '("" ""))
                          (org-agenda-prefix-format "%t%s")))
                      (tags-todo "+työ-@web" ((org-agenda-overriding-header "Työt") (org-agenda-skip-function #'my-org-agenda-skip-all-siblings-but-first)))
                      (tags-todo "+työ+@web" ((org-agenda-overriding-header "Selain") (org-agenda-skip-function #'my-org-agenda-skip-all-siblings-but-first)))
                      (tags-todo "+työ+puhelu" ((org-agenda-overriding-header "Puhelut") (org-agenda-skip-function #'my-org-agenda-skip-all-siblings-but-first)))
                      )
                     (
                     (org-agenda-remove-tags t)
                     (org-agenda-todo-keyword-format "")                  
                     (org-agenda-prefix-format "  %?-12t% s")
                     (org-agenda-compact-blocks t)
                     ))
                    ("Gh" "Agenda koti"
                     (
                       (agenda "" ((org-agenda-span 1)             ; daily agenda
                          (org-deadline-warning-days 7)            ; 7 day advanced warning for deadlines
                          (org-agenda-todo-keyword-format "")
                          (org-agenda-scheduled-leaders '("" ""))
                          (org-agenda-prefix-format "%t%s")))
                      (tags-todo "-työ-@web" ((org-agenda-overriding-header "Työt") (org-agenda-skip-function #'my-org-agenda-skip-all-siblings-but-first)))
                      (tags-todo "-työ+@web" ((org-agenda-overriding-header "Selain") (org-agenda-skip-function #'my-org-agenda-skip-all-siblings-but-first)))
                      (tags-todo "-työ+puhelu" ((org-agenda-overriding-header "Puhelut") (org-agenda-skip-function #'my-org-agenda-skip-all-siblings-but-first)))
                      )
                     (
                     (org-agenda-remove-tags t)
                     (org-agenda-todo-keyword-format "")                  
                     (org-agenda-prefix-format "  %?-12t% s")
                     (org-agenda-compact-blocks t)
                     ))
                    ))


        (defun my-org-agenda-skip-all-siblings-but-first ()
          "Skip all but the first non-done entry."
          (let (should-skip-entry)
            (unless (org-current-is-todo)
              (setq should-skip-entry t))
            (save-excursion
              (while (and (not should-skip-entry) (org-goto-sibling t))
              (when (org-current-is-todo)
                  (setq should-skip-entry t))))
            (when should-skip-entry
              (or (outline-next-heading)
                  (goto-char (point-max))))))

    (defun org-current-is-todo ()
          (string= "TODO" (org-get-todo-state)))

    (defun my-org-scheduled-for-today ()
           (ignore-errors
        (let ((subtree-end (save-excursion (org-end-of-subtree t)))
              (scheduled-day
                (time-to-days
                  (org-time-string-to-time
                    (org-entry-get nil "SCHEDULED"))))
              (now (time-to-days (current-time))))
           (and scheduled-day
                (not (= scheduled-day now))))))

    (defun my-org-agenda-skip-if-not-scheduled-today ()
    "If this function returns nil, the current match should not be skipped.
    Otherwise, the function must return a position from where the search
    should be continued."
    (ignore-errors
        (let ((subtree-end (save-excursion (org-end-of-subtree t)))
              (scheduled-day
                (time-to-days
                  (org-time-string-to-time
                    (org-entry-get nil "SCHEDULED"))))
              (now (time-to-days (current-time))))
           (and scheduled-day
                (not (= scheduled-day now))
                subtree-end))))

    (setq org-refile-targets '(("gtd.org.gpg"  :maxlevel . 1)
                               (org-agenda-files :tag . "prj")
                               ("polar-gtd.org.gpg" :maxlevel . 1)
                               ("someday.org.gpg" :maxlevel . 2)                             
                               ("polar-someday.org.gpg" :maxlevel . 2)))

    (setq org-tags-exclude-from-inheritance '("prj" "puhelu" "muistiinpano" "tapaaminen"))
      (setq org-stuck-projects '("+prj/-MAYBE-DONE-CANCELLED"
                                 ("TODO" "WAIT") ()))

      (defun my-org-with-entry ()
        (interactive)
        (save-excursion
          (org-entry-put nil "with" (read-string "With: " (org-entry-get nil "with")))))
      (global-set-key "\C-cw" 'my-org-with-entry)
#+END_SRC

I have created shell script [[file:sh/orgcapture.sh]] which opens Emacs in capture mode. I have also created service to
MacOS that uses the shell script when keyboard shortcut is used (see [[https://computers.tutsplus.com/tutorials/how-to-launch-any-app-with-a-keyboard-shortcut--mac-31463][instructions]]). Unfortunately Emacs catches all keys
and the same shortcut does not work within Emacs. Following binding enables the same shortcut in
Emacs.

#+BEGIN_SRC emacs-lisp 
  (global-set-key (kbd "C-S-s-o") 'org-capture)
#+END_SRC

** Calendar

See http://orgmode.org/worg/org-faq.html#Appointments/Diary

#+begin_src emacs-lisp 

(setq diary-file "~/org/diary")

(calendar-set-date-style 'european)

(setq calendar-week-start-day 1
      calendar-view-diary-initially-flag t
      calendar-mark-diary-entries-flag t)

(add-hook 'diary-display-hook 'diary-fancy-display)

#+end_src
** Emacsclient server

#+BEGIN_SRC emacs-lisp 
(setq server-socket-dir "~/.emacs.d/server")
(server-start)
#+END_SRC
** New prefix key: Control-q

~Control-q~ is bound to ~quoted-insert~ by default. That command is
not use so often and the key is perfectly located for prefix key.
So it is unset here to allow it to be re-used later.

#+BEGIN_SRC emacs-lisp 
  (global-unset-key (kbd "C-q"))
#+END_SRC

** Vertico, Marginalia, Consult, Orderless

#+BEGIN_SRC emacs-lisp
  (use-package vertico
  :straight t
  :straight t
  :init
  (vertico-mode))

  (use-package marginalia
  :straight t
  :straight t
  :init
  (marginalia-mode))

  (use-package consult
  :straight t
  :straight t
  :bind
  (("C-s" . consult-line)
   ("C-x b" . consult-buffer)
   ("M-y" . consult-yank-pop)))

  (use-package orderless
  :straight t
  :init
  (setq completion-styles '(orderless)))
#+END_SRC

** Corfu, Cape, Kind-icon

In-buffer completion UI via =completion-at-point= (capf). Corfu shows a popup
at point for code completion; Cape adds extra capf sources (dabbrev, file
names, keywords) so Corfu has something to complete even outside LSP buffers;
Kind-icon renders icons next to candidates indicating their kind (function,
variable, snippet, ...). This pairs with Vertico/Consult (same ecosystem,
same =orderless= filtering) and feeds directly off lsp-mode's
=lsp-completion-provider :capf=, so no LSP config changes are required.

#+BEGIN_SRC emacs-lisp
  (use-package corfu
    :straight t
    :init
    (global-corfu-mode)
    (corfu-popupinfo-mode)
    :custom
    (corfu-auto t)
    (corfu-auto-delay 0.15)
    (corfu-auto-prefix 2)
    (corfu-cycle t)
    (corfu-preselect 'prompt)
    (corfu-popupinfo-delay '(0.5 . 0.2)))

  (use-package cape
    :straight t
    :init
    (add-to-list 'completion-at-point-functions #'cape-dabbrev)
    (add-to-list 'completion-at-point-functions #'cape-file)
    (add-to-list 'completion-at-point-functions #'cape-keyword))

  (use-package kind-icon
    :straight t
    :after corfu
    :custom
    (kind-icon-default-face 'corfu-default)
    :config
    (add-to-list 'corfu-margin-formatters #'kind-icon-margin-formatter))
#+END_SRC

=orderless= works well during completion, but for capf it helps to let the
basic style match literal prefixes first, so LSP's own sorting is not
disrupted. Configure per-category overrides:

#+BEGIN_SRC emacs-lisp
  (setq completion-category-overrides
        '((file (styles basic partial-completion))
          (eglot (styles orderless))
          (lsp-capf (styles orderless))))
#+END_SRC

** Misc


#+BEGIN_SRC emacs-lisp
  ;;; turn on syntax highlighting
  (global-font-lock-mode 1)

  ;; Mustache mode
  (require 'mustache-mode)

  (defun iwb ()
    "indent whole buffer"
    (interactive)
    (delete-trailing-whitespace)
    (indent-region (point-min) (point-max) nil)
    (untabify (point-min) (point-max)))

  (defun previous-line-insert-newline ()
    "Moves line up and creates empty line"
    (interactive)
    (previous-line)
    (end-of-line)
    (newline-and-indent)
    )

  (defun next-line-insert-newline ()
    "Moves line up and creates empty line"
    (interactive)
    (end-of-line)
    (newline-and-indent)
    )

  (setq line-move-visual nil)
  (put 'scroll-left 'disabled nil)

  ;; (global-set-key (kbd "C-,") 'backward-paragraph)
  ;; (global-set-key (kbd "C-.") 'forward-paragraph)
  ;; (global-set-key  (kbd "C-`")    'shell-command)
  ;; (global-set-key  (kbd "M-`")    'shell-command-on-region)


  (global-set-key (kbd "C-c f") 'iwb)

  ;; Moving from window to window using arrows
  (global-set-key (kbd "<left>")  'windmove-left)
  (global-set-key (kbd "<right>") 'windmove-right)
  (global-set-key (kbd "<up>")    'windmove-up)
  (global-set-key (kbd "<down>")  'windmove-down)

  (global-set-key (kbd "M-n") 'next-line-insert-newline)
  (global-set-key (kbd "M-p") 'previous-line-insert-newline)



  (global-unset-key (kbd "C-<SPC>"))
  (global-set-key (kbd "C-<SPC>") 'set-mark-command)



  (global-set-key (kbd "s-<left>")  'windmove-left)
  (global-set-key (kbd "s-<right>") 'windmove-right)
  (global-set-key (kbd "s-<up>")    'windmove-up)
  (global-set-key (kbd "s-<down>")  'windmove-down)

  (put 'upcase-region 'disabled nil)
  (put 'scroll-left 'disabled nil)

  (global-set-key (kbd "C-q o")  'find-file-at-point)

  (global-set-key (kbd "C-q i")  'quoted-insert)
#+END_SRC

** Shell stuff 
*** Convient way to create new shell

I often need shell. But default ~M-x shell~ will throw back to the already
created shell. Many times this is not what I want.

#+begin_src emacs-lisp 
    (defun ps/open-new-shell ()
      (interactive)

      (let (
            (currentbuf (get-buffer-window (current-buffer)))
            (newbuf     (generate-new-buffer-name "*shell*"))
           )
       (generate-new-buffer newbuf)
       (set-window-dedicated-p currentbuf nil)
       (set-window-buffer currentbuf newbuf)
       (shell newbuf)
      )
    )
  (defun ps/open-new-local-shell ()
    "Open a new shell buffer in home directory."
    (interactive)
    (let ((default-directory "~/"))
          (ps/open-new-shell)))

  (global-set-key (kbd "C-q s")  'ps/open-new-shell)
  (global-set-key (kbd "C-q C-s")  'ps/open-new-local-shell)
#+end_src

*** Jumping to the root directory of repository

Sometimes it is convenient to jump to the root directory of the repository.

#+begin_src emacs-lisp 
(defun pw/shell-cd-to-vc-root ()
"Jumps to the root directory of version controled directory structure."
  (interactive)
  (let* ((proc (get-buffer-process (current-buffer)))
         (pmark (process-mark proc))
	 (started-at-pmark (= (point) (marker-position pmark)))         
         (root (vc-root-dir))
         (cmd (concat "cd " root)))
    (save-excursion
      (goto-char pmark)
      (unless comint-process-echoes     
         (insert cmd) (insert "\n"))
      (sit-for 0)			; force redisplay      
      (cd root)
      (comint-send-string proc cmd)
      (comint-send-string proc "\n")
      (set-marker pmark (point))
      )
    
    (if started-at-pmark (goto-char (marker-position pmark)))))

(defun pw/dired-cd-to-vc-root ()
(interactive)
(find-file (vc-root-dir)))

#+end_src

This function can be binded to key sequence when shell is activated.
#+begin_src emacs-lisp 
  (add-hook 'comint-mode-hook (lambda ()
                              (define-key comint-mode-map (kbd "C-q c r") 'pw/shell-cd-to-vc-root)
                              ))

  (add-hook 'dired-mode-hook (lambda ()
                              (define-key dired-mode-map (kbd "C-q c r") 'pw/dired-cd-to-vc-root)
                              ))

#+end_src
*** Fish-powered shell completion with annotations

Emacs =shell-mode= normally gets completions from bash, which provides
only bare candidate names without descriptions. The capf below calls
fish directly and returns a completion table with an annotation
function, so Corfu displays descriptions next to each candidate. Fish
must be installed (=apt install fish=) but is not used as the default
shell --- it runs behind the scenes only for completion queries.

#+begin_src emacs-lisp
  (defvar ps/fish-executable (executable-find "fish")
    "Path to the fish shell, or nil if not installed.")

  (defun ps/fish-completion-at-point ()
    "Completion-at-point function that queries fish for annotated candidates."
    (when (get-buffer-process (current-buffer))
      (let* ((end (point))
             (start (save-excursion
                      (skip-chars-backward "^ \t\n")
                      (point)))
             (line (buffer-substring-no-properties
                    (save-excursion (comint-bol) (point))
                    end))
             (raw (with-output-to-string
                    (with-current-buffer standard-output
                      (call-process ps/fish-executable nil t nil
                                    "-c" (format "complete -C%s"
                                                 (shell-quote-argument line))))))
             (results (mapcar (lambda (l)
                                (let ((parts (split-string l "\t")))
                                  (cons (car parts) (cadr parts))))
                              (split-string raw "\n" t))))
        (when results
          (list start end
                (mapcar #'car results)
                :annotation-function
                (lambda (c)
                  (when-let* ((desc (cdr (assoc c results))))
                    (concat "  " desc))))))))

  (if ps/fish-executable
      (add-hook 'shell-mode-hook
                (lambda ()
                  (add-hook 'completion-at-point-functions
                            #'ps/fish-completion-at-point nil t)))
    (display-warning 'fish-completion
                     "fish shell not found; install it for shell completion descriptions"
                     :warning))
#+end_src

*** GPTel autocomplete in shell-mode

GPTel autocomplete works in shell buffers with two safety guards:
it only triggers when the cursor is at the command prompt (after the
process mark, not up in scrollback) and when the shell is idle (no
command currently producing output).  Recent terminal output provides
context so the LLM can suggest commands informed by error messages,
directory listings, and other output.

#+begin_src emacs-lisp
  (defvar ps/gptel-shell-context-lines 100
    "Lines of recent shell output to include as context for gptel autocomplete.")

  (defvar ps/gptel-shell-idle-threshold 1.0
    "Seconds since last output before the shell is considered idle.")

  (defvar-local ps/shell-last-output-time nil
    "Time of last comint output in this buffer.")

  (defun ps/shell-track-output (&rest _)
    "Record the time of the latest shell output."
    (setq ps/shell-last-output-time (current-time)))

  (add-hook 'shell-mode-hook
            (lambda ()
              (add-hook 'comint-output-filter-functions
                        #'ps/shell-track-output nil t)))

  (defun ps/gptel-shell-idle-prompt-p ()
    "Non-nil when point is at an idle shell prompt."
    (and (derived-mode-p 'shell-mode)
         (comint-after-pmark-p)
         (or (null ps/shell-last-output-time)
             (> (float-time (time-since ps/shell-last-output-time))
                ps/gptel-shell-idle-threshold))))

  (defun ps/gptel-shell-guard (orig &rest args)
    "In shell-mode, only trigger gptel autocomplete at an idle prompt."
    (if (derived-mode-p 'shell-mode)
        (when (ps/gptel-shell-idle-prompt-p)
          (apply orig args))
      (apply orig args)))

  (defun ps/gptel-shell-context (orig &rest args)
    "Override context line count for shell-mode buffers."
    (if (derived-mode-p 'shell-mode)
        (let ((gptel-autocomplete-before-context-lines ps/gptel-shell-context-lines)
              (gptel-autocomplete-after-context-lines 0))
          (apply orig args))
      (apply orig args)))

  (advice-add 'gptel--post-command :around #'ps/gptel-shell-guard)
  (advice-add 'gptel-complete :around #'ps/gptel-shell-context)
#+end_src

*** No passwords in shell

#+BEGIN_SRC emacs-lisp
;; No passwords show in shell
(add-hook 'comint-output-filter-functions
          'comint-watch-for-password-prompt)
#+END_SRC

** Avy - for jumping around

#+BEGIN_SRC emacs-lisp
      (use-package avy
       :straight t
       :bind (
              ("C-." . avy-goto-char)
              ("C-q q". avy-pop-mark)))
#+END_SRC

#+BEGIN_SRC emacs-lisp :tangle no
  ;; 
  ;; enable a more powerful jump back function from ace jump mode
  ;;
  (autoload
    'ace-jump-mode-pop-mark
    "ace-jump-mode"
    "Ace jump back:-)"
    t)
  (eval-after-load "ace-jump-mode"
    '(ace-jump-mode-enable-mark-sync))
  (define-key global-map (kbd "C-q q") 'ace-jump-mode-pop-mark)
  (define-key global-map (kbd "C-.") 'ace-jump-mode)
#+END_SRC
** Smart jump back

Pop the global mark ring, but reuse an existing window if the target buffer is
already visible rather than switching the current window's buffer.

#+BEGIN_SRC emacs-lisp
  (defun my/pop-global-mark-smart ()
    "Pop global mark, reusing existing window if buffer is already visible."
    (interactive)
    (let ((ring global-mark-ring))
      (while (and ring (not (marker-buffer (car ring))))
        (setq global-mark-ring (cdr global-mark-ring))
        (setq ring global-mark-ring))
      (if (not ring)
          (message "No global mark set")
        (let* ((mark (car ring))
               (buf (marker-buffer mark))
               (pos (marker-position mark))
               (win (get-buffer-window buf)))
          (setq global-mark-ring (nconc (cdr ring) (list mark)))
          (if win
              (progn (select-window win) (goto-char pos))
            (switch-to-buffer buf)
            (goto-char pos))))))

  (global-set-key (kbd "C-x C-SPC") #'my/pop-global-mark-smart)
#+END_SRC

** COMMENT File editing modes
*** COMMENT CSV-mode
#+BEGIN_SRC emacs-lisp 
;; CSV Mode
(el-get-bundle csv-mode)
(require 'csv-mode)
#+END_SRC
*** COMMENT Docker-mode
#+BEGIN_SRC emacs-lisp 
(el-get-bundle dockerfile-mode)
;;; Dockerfile mode
(require 'dockerfile-mode)
(add-to-list 'auto-mode-alist '("Dockerfile\\'" . dockerfile-mode))
#+END_SRC
*** Yaml-mode
#+BEGIN_SRC emacs-lisp 
(el-get-bundle yaml-mode)
#+END_SRC
** COMMENT Edit server

Edit server allows editing content from web browser. See for example [[https://chrome.google.com/webstore/detail/edit-with-emacs/ljobjlafonikaiipfkggjbhkghgicgoh][edit-with-emacs]] Chrome extension.

This is disabled as there seems to be some kind of load problem at the moment [2020-04-14].

#+BEGIN_SRC emacs-lisp :tangle no
(el-get-bundle edit-server)
(edit-server-start)
#+END_SRC

** COMMENT Expand region
#+BEGIN_SRC emacs-lisp 
(el-get-bundle expand-region)
(require 'expand-region)
(global-set-key (kbd "C-q C-e") 'er/expand-region)
#+END_SRC
** COMMENT Setup Go environment


#+BEGIN_SRC emacs-lisp 
(defun system-has-go () "Tests wether go is installed or not" 
       (condition-case nil
           (progn
             (start-process "" nil "go")
             t
             )
         (error nil))
       )
(defun makeinfo-version () "Make info version"
       (with-temp-buffer
          (call-process "makeinfo" nil t nil "--version")
          (goto-char (point-min))
          (re-search-forward "[0-9]\\{1,2\\}\\(\\.[0-9]\\{1,2\\}\\)\\{1,2\\}")
          (let ((s (match-beginning 0)) (e (point)))
            (mapcar
             'string-to-number
             (split-string (buffer-substring s e) "\\.")))))

(defun setup-go () "Install go environment with el-get"
       (el-get-bundle go-mode)
       (el-get-bundle dash)
       
       ;; Require makeinfo which major version is 5 or more
       (if (< 4 (car (makeinfo-version)))
           (progn
           (el-get-bundle flycheck)   
           ;; go get github.com/dougm/goflymake
           (add-to-list 'load-path "~/src/github.com/dougm/goflymake")
           (require 'go-flycheck))
           ))

       ;; go get github.com/nsf/gocode
       (el-get-bundle go-autocomplete)
       (require 'go-autocomplete)

       (add-hook 'go-mode-hook 
                 (lambda ()
                   (define-key go-mode-map (kbd "C-q j") 'godef-jump)
                   (define-key go-mode-map (kbd "C-q q") 'pop-global-mark)
                   (add-hook 'before-save-hook 'gofmt-before-save))
                 )

(if (system-has-go) (setup-go))
#+END_SRC

** COMMENT Multicursors
#+BEGIN_SRC emacs-lisp 
(el-get-bundle multiple-cursors)

(global-set-key (kbd "C-c m <return>") 'set-rectangular-region-anchor)
(global-set-key (kbd "C-c m c") 'mc/edit-lines)
(global-set-key (kbd "C-c m a") 'mc/mark-all-like-this)
(global-set-key (kbd "C-c m .") 'mc/mark-next-like-this)
(global-set-key (kbd "C-c m ,") 'mc/mark-previous-like-this)
(global-set-key (kbd "C-c m m") 'mc/mark-more-like-this-extended)
#+END_SRC

** COMMENT Yasniplet and autocomplete
#+BEGIN_SRC emacs-lisp 
(el-get-bundle yasnippet)
(el-get-bundle auto-complete)


(require 'yasnippet)
(require 'auto-complete)
(require 'auto-complete-config)
;;(require 'auto-complete-yasnippet)

(ac-config-default)
;(global-set-key (kbd "C-<tab>")  'yas-expand)

(setq ac-source-yasnippet nil)

;;; auto complete mod
;;; should be loaded after yasnippet so that they can work together

(add-to-list 'ac-dictionary-directories "~/.emacs.d/ac-dict")

;;; set the trigger key so that it can work together with yasnippet on tab key,
;;; if the word exists in yasnippet, pressing tab will cause yasnippet to
;;; activate, otherwise, auto-complete will
(ac-set-trigger-key "<tab>")



;; (setq-default ac-sources
;;       '(
;;         ;; ac-source-semantic
;;         ac-source-yasnippet
;;         ac-source-abbrev
;;         ac-source-words-in-buffer
;;         ac-source-words-in-all-buffer
;;         ;; ac-source-imenu
;;         ac-source-files-in-current-dir
;;         ac-source-filename
;;         )
;;       )

(yas-global-mode 1)
(global-auto-complete-mode 1)

#+END_SRC
** Buffer switching

One common task is to switch between two buffers.
Suspend frame is not very usefull command so, it is
recycled to change the buffer.

#+begin_src emacs-lisp 
(global-set-key (kbd "C-z")  'mode-line-other-buffer)
#+end_src

** IBuffers

#+begin_src emacs-lisp 
   (global-set-key (kbd "C-x C-b") 'ibuffer)
   (autoload 'ibuffer "ibuffer" "List buffers." t)

    (setq ibuffer-saved-filter-groups
            (quote (("default"
                     ("dired" (mode . dired-mode))
                     ("org" (or
                             (mode . org-mode)
                             (mode . org-agenda-mode)                           
                             ))
                     ("emacs" (or
                               (name . "^\\*scratch\\*$")
                               (name . "^\\*Messages\\*$")))
                     ("shell" (or
                              (mode . shell-mode)
                              (mode . term-mode)
                              ))))))

#+end_src

** COMMENT WCheck mode

Set up wcheck mode for spell checking

#+BEGIN_SRC emacs-lisp
  (el-get-bundle 'wcheck-mode)
  (global-set-key (kbd "C-x w") 'wcheck-mode)
  (add-hook 'wcheck-mode-hook
            (lambda ()
              (define-key wcheck-mode-map (kbd "C-q l") 'wcheck-change-language)
              (define-key wcheck-mode-map (kbd "C-q c") 'wcheck-actions)
              (define-key wcheck-mode-map (kbd "C-q n") 'wcheck-jump-forward)
              (define-key wcheck-mode-map (kbd "C-q p") 'wcheck-jump-backward)
              ))

  (setq wcheck-language-data
        '(
          ("British English"
           (program . "/usr/bin/enchant")
           (args "-l" "-d" "british")
           (action-program . "/usr/bin/ispell")
           (action-args "-a" "-d" "british")
           (action-parser . wcheck-parser-ispell-suggestions))

          ("Finnish"
           (program . "/usr/bin/enchant")
           (args "-l" "-d" "fi")
           (action-program . "/usr/bin/enchant")
           (action-args "-a" "-d" "fi")
           (action-parser . wcheck-parser-ispell-suggestions))

          ))

  (wcheck-change-language "British English" 'GLOBAL)

#+END_SRC

** Ediff

Keep everything in a single frame — no separate control frame.

#+begin_src emacs-lisp
(setq ediff-window-setup-function 'ediff-setup-windows-plain)
#+end_src

** Magit for using git

#+BEGIN_SRC emacs-lisp
  (use-package magit
    :straight t
    :bind ("C-x g" . magit-status))

  (use-package treemacs-magit  :straight t :after (treemacs magit))
#+END_SRC

** Compilation

Scroll the compilation buffer to follow output as it arrives. On a successful
build, automatically close the compilation window after a short delay.

#+BEGIN_SRC emacs-lisp
  (setq compilation-scroll-output t)

  (defun my/compilation-auto-close (buf status)
    (when (string= status "finished\n")
      (run-at-time 2 nil
                   (lambda ()
                     (when-let (win (get-buffer-window buf t))
                       (delete-window win))))))

  (add-hook 'compilation-finish-functions #'my/compilation-auto-close)
#+END_SRC

** Projectile

Project management with automatic project type detection. Projectile recognises
build files (=Makefile=, =pom.xml=, =build.gradle=, =package.json=,
=Cargo.toml=, etc.) and provides compile, test, and run commands for each. The
keymap is bound to =C-c p=.

#+BEGIN_SRC emacs-lisp
  (use-package projectile
    :straight t
    :init
    (projectile-mode +1)
    :config
    (setq compilation-read-command nil)
    (setq projectile-project-search-path '("~/src"))
    (projectile-add-known-project "~/.emacs.d/")
    :bind-keymap
    ("C-c p" . projectile-command-map))
#+END_SRC

** LSP Mode

Language Server Protocol support for code intelligence features. LSP keybindings
are under =C-c l= prefix. Completion uses =completion-at-point= (capf) so it
integrates with whatever completion framework is active (e.g. Vertico/Corfu).

=lsp-completion-provider= is set to =:none= so lsp-mode does not attempt to
autoconfigure company-mode (which would emit a warning on every LSP start
when Corfu is used instead). =lsp-completion-mode= still registers
=lsp-completion-at-point= into =completion-at-point-functions=, which Corfu
picks up.

#+BEGIN_SRC emacs-lisp
(setenv "LSP_USE_PLISTS" "true")
(setq lsp-use-plists t)

(use-package lsp-mode
  :straight t
  :commands (lsp lsp-deferred)
  :init
  (setq lsp-keymap-prefix "C-c l")
  :config
  (setq lsp-enable-snippet t
        lsp-enable-symbol-highlighting t
        lsp-enable-links t
        lsp-signature-auto-activate t
        lsp-signature-render-documentation t
        lsp-headerline-breadcrumb-enable t
        lsp-modeline-code-actions-enable t
        lsp-diagnostics-provider :auto
        lsp-completion-provider :none
        lsp-idle-delay 0.5)
  :hook
  ((lsp-mode . lsp-enable-which-key-integration)))

(use-package lsp-ui
  :straight t
  :commands lsp-ui-mode
  :config
  (setq lsp-ui-doc-enable t
        lsp-ui-doc-position 'at-point
        lsp-ui-doc-show-with-cursor t
        lsp-ui-sideline-enable t
        lsp-ui-sideline-show-hover t))

(use-package lsp-treemacs
  :straight t
  :after (lsp-mode treemacs)
  :commands lsp-treemacs-errors-list)
#+END_SRC

*** Consult-LSP Integration

Integrates LSP with the Consult completion framework, providing fuzzy search
for symbols and diagnostics. Key commands:

- =consult-lsp-symbols= -- Search for symbols in the workspace
- =consult-lsp-diagnostics= -- Browse diagnostics with Consult
- =consult-lsp-file-symbols= -- Search for symbols in the current file

#+BEGIN_SRC emacs-lisp
  (use-package consult-lsp
    :straight t
    :after (consult lsp-mode)
    :commands (consult-lsp-symbols consult-lsp-diagnostics consult-lsp-file-symbols))
#+END_SRC

*** LSP Booster

[[https://github.com/blahgeek/emacs-lsp-booster][emacs-lsp-booster]] is an external program that wraps any LSP server to
accelerate communication between Emacs and the server. It works by converting
JSON messages from the language server into Emacs bytecode, which Emacs can
evaluate significantly faster than it can parse raw JSON. This is especially
noticeable with heavy language servers like =jdtls= (Java) that produce large
responses.

The integration requires two pieces of advice:

1. *JSON parsing advice* -- When the booster is active, server responses arrive
   as Emacs bytecode (prefixed with =#=) rather than JSON. This advice checks
   for that prefix and evaluates the bytecode directly, falling back to normal
   JSON parsing for unmodified responses. It advises either =json-parse-buffer=
   (native JSON, Emacs 27+) or =json-read= (older Emacs), depending on which
   is available.

2. *Command wrapping advice* -- This advises =lsp-resolve-final-command= to
   prepend =emacs-lsp-booster= to the server launch command, so the booster
   acts as a transparent proxy between Emacs and the actual server process. It
   only activates when all of the following are true:
   - The =emacs-lsp-booster= binary is found on =PATH=
   - The directory is local (not a TRAMP remote connection)
   - Emacs is not using native JSON-RPC (Emacs 30+ built-in LSP support)
   - It is not a test/dry-run invocation

If =emacs-lsp-booster= is not installed, the advice functions are inert and LSP
works exactly as it would without them.

**** Automatic installation

The following function automatically downloads the latest pre-built binary from
GitHub when =emacs-lsp-booster= is not found on =PATH=. It queries the GitHub
releases API to find the latest version, selects the correct archive for the
current platform (Linux or macOS, x86_64 only), downloads and extracts it to
=~/.emacs.d/lsp-booster/=, and makes it executable. The download happens
asynchronously so it does not block Emacs startup -- a message is displayed when
the installation completes. On subsequent startups where the binary already
exists, this function does nothing.

You can also install manually if you prefer:

#+BEGIN_EXAMPLE
  # With Cargo (Rust toolchain required):
  cargo install emacs-lsp-booster

  # Or download a pre-built binary from the GitHub releases page
  # and place it somewhere on PATH.
#+END_EXAMPLE

#+BEGIN_SRC emacs-lisp
  (defvar lsp-booster-install-dir
    (expand-file-name "lsp-booster" user-emacs-directory)
    "Directory where emacs-lsp-booster binary will be installed.")

  (defun lsp-booster--github-asset-name ()
    "Return the expected release asset name suffix for this platform."
    (let ((arch (car (split-string system-configuration "-"))))
      (cond
       ((and (eq system-type 'gnu/linux) (string= arch "x86_64"))
        "x86_64-unknown-linux-musl.zip")
       ((and (eq system-type 'darwin) (string= arch "x86_64"))
        "x86_64-apple-darwin.zip")
       (t nil))))

  (defun lsp-booster--ensure-installed ()
    "Download and install emacs-lsp-booster if not already on PATH.
Queries the GitHub releases API for the latest version, downloads
the appropriate pre-built binary, and extracts it to `lsp-booster-install-dir'."
    (when (and (not (executable-find "emacs-lsp-booster"))
               (lsp-booster--github-asset-name))
      (let ((install-dir lsp-booster-install-dir))
        (unless (file-directory-p install-dir)
          (make-directory install-dir t))
        (unless (member install-dir exec-path)
          (add-to-list 'exec-path install-dir)
          (setenv "PATH" (concat install-dir ":" (getenv "PATH"))))
        (message "emacs-lsp-booster not found, downloading from GitHub...")
        (url-retrieve
         "https://api.github.com/repos/blahgeek/emacs-lsp-booster/releases/latest"
         (lambda (_status)
           (goto-char url-http-end-of-headers)
           (let* ((release (json-parse-buffer :object-type 'alist))
                  (assets (alist-get 'assets release))
                  (suffix (lsp-booster--github-asset-name))
                  (asset (seq-find
                          (lambda (a)
                            (and (string-suffix-p suffix (alist-get 'name a))
                                 (not (string-suffix-p ".sha256sum" (alist-get 'name a)))))
                          assets))
                  (url (alist-get 'browser_download_url asset)))
             (if (not url)
                 (message "emacs-lsp-booster: no matching release asset found for %s" suffix)
               (let ((zip-file (expand-file-name "emacs-lsp-booster.zip" temporary-file-directory)))
                 (url-copy-file url zip-file t)
                 (call-process "unzip" nil nil nil "-o" zip-file "-d" lsp-booster-install-dir)
                 (let ((binary (expand-file-name "emacs-lsp-booster" lsp-booster-install-dir)))
                   (set-file-modes binary #o755)
                   (delete-file zip-file)
                   (message "emacs-lsp-booster installed to %s" binary))))))
         nil t))))

  (lsp-booster--ensure-installed)
#+END_SRC

**** Advice functions

#+BEGIN_SRC emacs-lisp
  (defun lsp-booster--advice-json-parse (old-fn &rest args)
    "Try to parse bytecode instead of json."
    (or
     (when (equal (following-char) ?#)
       (let ((bytecode (read (current-buffer))))
         (when (byte-code-function-p bytecode)
           (funcall bytecode))))
     (apply old-fn args)))
  (advice-add (if (progn (require 'json)
                         (fboundp 'json-parse-buffer))
                  'json-parse-buffer
                'json-read)
              :around
              #'lsp-booster--advice-json-parse)

  (defun lsp-booster--advice-final-command (old-fn cmd &optional test?)
    "Prepend emacs-lsp-booster command to lsp CMD."
    (let ((orig-result (funcall old-fn cmd test?)))
      (if (and (not test?)
               (not (file-remote-p default-directory))
               (not (functionp 'json-rpc-connection))
               (executable-find "emacs-lsp-booster"))
          (progn
            (message "Using emacs-lsp-booster for %s!" orig-result)
            (cons "emacs-lsp-booster" orig-result))
        orig-result)))
  (advice-add 'lsp-resolve-final-command :around #'lsp-booster--advice-final-command)
#+END_SRC

** Java Development (LSP Java)

Java language support using Eclipse JDT Language Server. The server will be
downloaded and installed automatically on first use.

*** Auto-detecting installed JDKs

Previously =lsp-java-configuration-runtimes= listed JDK paths by hand, which
produced warnings such as /Invalid runtime for JavaSE-1.8: The path points to a
missing or inaccessible folder/ whenever the machine did not ship that exact
version. The helpers below scan the usual JVM install roots and build the
runtime vector dynamically:

- =/usr/lib/jvm= -- Debian, Ubuntu, Fedora
- =/usr/java= -- Oracle RPM installs
- =/Library/Java/JavaVirtualMachines= -- macOS (with =Contents/Home= handled)

Each directory name matching =java-N=, =jdk-N=, or =openjdk-N= (optionally
prefixed with =1.= for the legacy Java 8 layout) is turned into a
=JavaSE-<version>= entry. The newest detected version is marked as the default
runtime, and the same JDK is used as =lsp-java-java-path= to launch the JDT
server itself. Symlinks like Debian's =default-java= are skipped so that each
version appears only once.

#+BEGIN_SRC emacs-lisp
(use-package lsp-java
  :straight t
  :after lsp-mode
  :preface
  (defun my/detect-java-runtimes ()
    "Return a vector for `lsp-java-configuration-runtimes' by scanning
common JVM install roots.  Each detected JDK becomes a JavaSE-<version>
entry; the newest version is marked as default."
    (let* ((roots '("/usr/lib/jvm"
                    "/usr/java"
                    "/Library/Java/JavaVirtualMachines"))
           (re "\\`\\(?:java-\\|jdk-?\\|openjdk-\\)\\(?:1\\.\\)?\\([0-9]+\\)")
           (best (make-hash-table :test 'eql)))
      (dolist (root roots)
        (when (file-directory-p root)
          (dolist (entry (directory-files root t "\\`[^.]"))
            (let ((base (file-name-nondirectory entry)))
              (when (and (file-directory-p entry)
                         (not (file-symlink-p entry))
                         (string-match re base))
                (let* ((ver (string-to-number (match-string 1 base)))
                       (mac-home (expand-file-name "Contents/Home" entry))
                       (home (if (file-directory-p mac-home) mac-home entry))
                       (java-bin (expand-file-name "bin/java" home))
                       (existing (gethash ver best)))
                  (when (and (file-executable-p java-bin)
                             (or (null existing)
                                 (< (length home) (length existing))))
                    (puthash ver home best))))))))
      (let* ((versions (sort (hash-table-keys best) #'<))
             (newest (car (last versions))))
        (apply #'vector
               (mapcar (lambda (v)
                         (let ((name (format "JavaSE-%s" (if (= v 8) "1.8" v)))
                               (path (gethash v best)))
                           (if (= v newest)
                               (list :name name :path path :default t)
                             (list :name name :path path))))
                       versions)))))

  (defun my/detect-java-path ()
    "Path of the newest `java' executable detected by
`my/detect-java-runtimes', or nil when no JDK is found."
    (let ((default (seq-find (lambda (r) (plist-get r :default))
                             (append (my/detect-java-runtimes) nil))))
      (when default
        (expand-file-name "bin/java" (plist-get default :path)))))
  :config
  (setq lsp-java-server-install-dir "~/.emacs.d/lsp-java/"
        lsp-java-workspace-dir (expand-file-name "~/.emacs.d/lsp-java-workspace/")
        lsp-java-import-gradle-enabled t
        lsp-java-import-maven-enabled t
        lsp-java-maven-download-sources t
        lsp-java-autobuild-enabled t
        lsp-java-format-enabled t
        lsp-java-format-settings-url nil
        lsp-java-format-settings-profile nil
        lsp-java-code-generation-use-blocks t)
  (let ((runtimes (my/detect-java-runtimes))
        (java-path (my/detect-java-path)))
    (when (> (length runtimes) 0)
      (setq lsp-java-configuration-runtimes runtimes))
    (when java-path
      (setq lsp-java-java-path java-path)))
  :hook
  (java-mode . (lambda ()
                 (require 'lsp-java)
                 (lsp-deferred))))
#+END_SRC

Machine-specific overrides (for example adding a runtime installed in a
non-standard location) belong in =local-init.el=; just =setq= the two variables
after this block has run.

** COMMENT Kill buffer instead of burying it

#+begin_src emacs-lisp 
(defadvice quit-window (before quit-window-always-kill)
  "When running `quit-window', always kill the buffer."
  (ad-set-arg 0 t))
(ad-activate 'quit-window)
#+end_src
** Default column width 80 characters
#+begin_src emacs-lisp 
(setq default-fill-column 80)
#+end_src

** Don't confirm kills

#+BEGIN_SRC emacs-lisp

  (global-set-key (kbd "C-x k")
                (lambda () (interactive) (kill-this-buffer)))
#+END_SRC

** Protocol Buffers  mode

[[https://developers.google.com/protocol-buffers/docs/overview][Google Protocol Buffers]] is way to serialize data. It uses "proto" files to describe serialization format.

#+begin_src emacs-lisp 
(require 'protobuf-mode)
(add-to-list 'auto-mode-alist '("\\.proto\\'" . protobuf-mode))
#+end_src

** Open current buffer in idea
#+begin_src emacs-lisp 
  (defun open-buffer-curent-idea ()
    ""
    (interactive)
    (call-process "idea" nil nil nil (buffer-file-name))
    (if (string-equal system-type "darwin")
        (ns-do-applescript "tell application \"IntelliJ Idea\" to activate")
      )
  )

  (global-set-key (kbd "C-q C-o")  'open-buffer-curent-idea)
#+end_src

** Toggle transparency of current frame

Sometime it is nice to look what is behind the frame. Following code toggles frame to be almost completely transparent
and back to solid again. 
#+begin_src emacs-lisp 
  (defun ps/toggle-transparency ()
    "Toggles frame transparency."
    (interactive)
    (if (equal '(100 100) (frame-parameter (selected-frame) 'alpha))
        (set-frame-parameter (selected-frame) 'alpha '(10 10))
      (set-frame-parameter (selected-frame) 'alpha '(100 100))))

  (global-set-key (kbd "C-q t")  'ps/toggle-transparency)
#+end_src

** PlantUML support

PlantUML works using JAR. Next is function that will load the jar if it is missing. Function returns the path where the
jar was loaded.

#+begin_src emacs-lisp 
  (defun pw/download-plantuml-jar-if-needed () ""
         (let ((plantuml-jar "~/.emacs.d/plantuml.jar"))
           (if (not (file-exists-p plantuml-jar))
               (progn
                 (url-copy-file "http://downloads.sourceforge.net/project/plantuml/plantuml.jar?r=http%3A%2F%2Fplantuml.com%2Fdownload.html&ts=1441279540&use_mirror=netix" plantuml-jar)
                 ))
           (expand-file-name plantuml-jar)))
#+end_src

#+begin_src emacs-lisp
  (use-package deflate
    :straight (deflate :type git :host github :repo "skuro/deflate"))

    (use-package plantuml-mode
      :straight (plantuml-mode :type git :host github :repo "skuro/plantuml-mode")
      :mode ("\\.plantuml\\'" "\\.puml\\'")
      :config
      (setq plantuml-default-exec-mode 'jar
            org-plantuml-jar-path (pw/download-plantuml-jar-if-needed)
            plantuml-jar-path (pw/download-plantuml-jar-if-needed)))
#+end_src

Now we can set the PlantUML jar for org-mode.
#+begin_src emacs-lisp 
;; Don`t confirm plant uml runs for conviency.
(let ((default-confirm org-confirm-babel-evaluate))
  (defun my-org-confirm-babel-evaluate (lang body)
    (if (string= lang "plantuml") nil default-confirm))
  (setq org-confirm-babel-evaluate 'my-org-confirm-babel-evaluate)
  )

(add-hook 'org-babel-after-execute-hook 'org-display-inline-images)
(setq org-startup-with-inline-images t)
(setq plantuml-indent-level 2)
(setq org-src-tab-acts-natively t)
(setq org-edit-src-content-indentation 0)
#+end_src
** AI tool setup

This section configures AI tools (gptel, ellama, aidermacs, Claude Code) for use with
different LLM backends. The configuration is designed to be machine-independent by using
variables that can be overridden in =local-pre-init.el=.

*** Machine-Dependent Configuration

The following variables control which LLM backend is used and should be set in
=~/.emacs.d/local-pre-init.el= before this configuration loads:

**** Work Machine Example (Bedrock + Ollama)
#+BEGIN_EXAMPLE emacs-lisp
;; In local-pre-init.el for work machine:
;; Use AWS Bedrock for main chat, Ollama for autocomplete

;; Ollama configuration (for autocomplete)
(defvar my/ollama-host-name "127.0.0.1")
(defvar my/ollama-port 11434)
(defvar my/ollama-chat-model "gpt-oss:20b")
(defvar my/ollama-fast-model "llama3.1:8b")
(defvar my/ollama-utility-model "qwen2.5-coder:14b")
(defvar my/ollama-embedding-model "nomic-embed-text")

;; Use Bedrock for gptel
(defvar my/use-bedrock-gptel t)
(defvar my/bedrock-region "eu-west-1")
(defvar my/bedrock-model-region 'eu)
(defvar my/bedrock-model 'claude-opus-4-6)

;; Use Ollama for autocomplete
(defvar my/use-ollama-autocomplete t)
#+END_EXAMPLE

**** Personal Machine Example (Claude API + Ollama)
#+BEGIN_EXAMPLE emacs-lisp
;; In local-pre-init.el for personal machine:
;; Use Claude API directly, Ollama for autocomplete

;; Ollama configuration (for autocomplete and ellama)
(defvar my/ollama-host-name "127.0.0.1")
(defvar my/ollama-port 11434)
(defvar my/ollama-chat-model "gpt-oss:20b")
(defvar my/ollama-fast-model "llama3.1:8b")
(defvar my/ollama-utility-model "qwen2.5-coder:14b")
(defvar my/ollama-embedding-model "nomic-embed-text")

;; Use Claude API for gptel
(defvar my/use-bedrock-gptel nil)
(defvar my/claude-api-key "your-api-key-here")  ; Or use auth-source
(defvar my/claude-model 'claude-sonnet-4-20250514)

;; Use Ollama for autocomplete
(defvar my/use-ollama-autocomplete t)
#+END_EXAMPLE

*** Default Values (used if not set in local-pre-init.el)

#+begin_src emacs-lisp
;; Ollama host configuration
(unless (boundp 'my/ollama-host-name)
  (defvar my/ollama-host-name "127.0.0.1"))
(unless (boundp 'my/ollama-port)
  (defvar my/ollama-port 11434))

;; Ollama model names
(unless (boundp 'my/ollama-chat-model)
  (defvar my/ollama-chat-model "gpt-oss:20b"))
(unless (boundp 'my/ollama-fast-model)
  (defvar my/ollama-fast-model "llama3.1:8b"))
(unless (boundp 'my/ollama-utility-model)
  (defvar my/ollama-utility-model "qwen2.5-coder:14b"))
(unless (boundp 'my/ollama-embedding-model)
  (defvar my/ollama-embedding-model "nomic-embed-text"))

;; Derived variable
(defvar my/ollama-host
  (format "%s:%d" my/ollama-host-name my/ollama-port))

;; Backend selection defaults
(unless (boundp 'my/use-bedrock-gptel)
  (defvar my/use-bedrock-gptel t))  ; Default to Bedrock
(unless (boundp 'my/use-ollama-autocomplete)
  (defvar my/use-ollama-autocomplete t))

;; Bedrock configuration defaults
(unless (boundp 'my/bedrock-region)
  (defvar my/bedrock-region "us-east-1"))
(unless (boundp 'my/bedrock-model-region)
  (defvar my/bedrock-model-region 'us))
(unless (boundp 'my/bedrock-model)
  (defvar my/bedrock-model 'claude-sonnet-4-20250514))

;; Claude API configuration defaults
(unless (boundp 'my/claude-api-key)
  (defvar my/claude-api-key nil))  ; Should be set in local-pre-init.el
(unless (boundp 'my/claude-model)
  (defvar my/claude-model 'claude-sonnet-4-20250514))
#+end_src

*** AI keymap
#+begin_src emacs-lisp
(define-prefix-command 'my/ai-map)
(global-set-key (kbd "C-q a") #'my/ai-map)
#+end_src

*** gptel

Configure gptel to use either Bedrock or Claude API based on machine configuration.

#+begin_src emacs-lisp
(use-package gptel
  :straight t
  :straight t
  :commands (gptel gptel-send gptel-rewrite)
  :init
  ;; Always set up Ollama backend (might be used for autocomplete)
  (setq my/gptel-ollama
        (gptel-make-ollama
         "Ollama"
         :host my/ollama-host
         :stream t
         :models (mapcar #'intern
                        (list my/ollama-chat-model
                              my/ollama-fast-model
                              my/ollama-utility-model))))

  ;; Set up the main backend based on configuration
  (if my/use-bedrock-gptel
      ;; Use AWS Bedrock
      (progn
        (setq my/gptel-main-backend
              (gptel-make-bedrock
               "Claude-Bedrock"
               :stream t
               :region 'eu-west-1'
               :model-region 'eu
               :models '(claude-opus-4-6
                 claude-sonnet-4-20250514
                 claude-haiku-4-5-20251001)))               

        (setq my/gptel-main-model my/bedrock-model))
    ;; Use Claude API directly
    (progn
      (setq my/gptel-main-backend
            (gptel-make-anthropic
             "Claude"
             :stream t
             :key my/claude-api-key))  ; Can also use 'gptel-api-key for auth-source
      (setq my/gptel-main-model my/claude-model)))

  :config
  (setq gptel-backend my/gptel-main-backend)
  (setq gptel-model my/gptel-main-model)
  (setq gptel-default-mode 'org-mode)
  (setq gptel-track-response nil)

  (define-key my/ai-map (kbd "c") #'gptel)
  (define-key my/ai-map (kbd "s") #'gptel-send)
  (define-key my/ai-map (kbd "r") #'gptel-rewrite))
#+end_src

*** aidermacs

Aider configuration uses environment variables =AIDER_MODEL= and =AIDER_WEAK_MODEL=.
These should be set in your shell profile or in =local-pre-init.el= using:

#+BEGIN_EXAMPLE emacs-lisp
;; In local-pre-init.el (optional, if not set in shell):
(setenv "AIDER_MODEL" "bedrock/anthropic.claude-sonnet-4-20250514-v1:0")
(setenv "AIDER_WEAK_MODEL" "bedrock/anthropic.claude-3-5-haiku-20241022-v1:0")
;; or for personal machine:
(setenv "AIDER_MODEL" "claude-sonnet-4-20250514")
(setenv "AIDER_WEAK_MODEL" "claude-3-5-haiku-20241022")
#+END_EXAMPLE

#+begin_src emacs-lisp
(use-package aidermacs
  :straight t
  :commands (aidermacs-transient-menu aidermacs-run-aider)
  :init
  (setq aidermacs-default-chat-mode 'architect)
  (setq aidermacs-use-voice nil)
  :config
  (setq aidermacs-default-model (exec-path-from-shell-getenv "AIDER_MODEL"))
  (setq aidermacs-weak-model (exec-path-from-shell-getenv "AIDER_WEAK_MODEL"))
  (define-key my/ai-map (kbd "a") #'aidermacs-transient-menu))
#+end_src

*** aidermacs / git helper
#+begin_src emacs-lisp
(defun my/git-diff-staged-to-buffer ()
  "Show staged git diff in a temp buffer."
  (interactive)
  (let ((buf (get-buffer-create "*git-staged-diff*")))
    (with-current-buffer buf
      (erase-buffer)
      (call-process "git" nil buf nil "diff" "--staged")
      (diff-mode))
    (pop-to-buffer buf)))

(define-key my/ai-map (kbd "d") #'my/git-diff-staged-to-buffer)
#+end_src

*** ellama
#+begin_src emacs-lisp
(use-package llm
  :straight t
  :straight t)

(use-package ellama
  :straight t
  :straight t
  :after llm
  :config
  (require 'llm-ollama)

  (setq ellama-provider
        (make-llm-ollama
         :host my/ollama-host-name
         :port my/ollama-port
         :chat-model my/ollama-utility-model
         :embedding-model my/ollama-embedding-model))


  (setq ellama-language "English")
  (setq ellama-naming-provider ellama-provider)
  (setq ellama-summarization-provider ellama-provider)

  (define-key my/ai-map (kbd "e") #'ellama)
  (define-key my/ai-map (kbd "i") #'ellama-improve-wording)
  (define-key my/ai-map (kbd "m") #'ellama-summarize))
#+end_src

*** gptel autocomplete

Autocomplete can use either Ollama (faster, local) or the main backend.
Set =my/use-ollama-autocomplete= in =local-pre-init.el= to control this.

#+begin_src emacs-lisp
;; Set up autocomplete backend based on configuration
(when my/use-ollama-autocomplete
  (setq my/gptel-autocompletion-backend
        (gptel-make-ollama
         "autocomplete"
         :host my/ollama-host
         :models (list my/ollama-utility-model))))

;; If not using Ollama, use the main backend
(unless (boundp 'my/gptel-autocompletion-backend)
  (setq my/gptel-autocompletion-backend my/gptel-main-backend))

(use-package gptel-autocomplete
  :straight '(:type git :host github :repo "JDNdeveloper/gptel-autocomplete")
  :config
  (require 'gptel-autocomplete)
  (setq gptel-autocomplete-before-context-lines 100
        gptel-autocomplete-after-context-lines 20
        gptel-autocomplete-temperature 0.1
        gptel-autocomplete-use-context t
        gptel-autocomplete-idle-delay 0)
  (keymap-set gptel-autocomplete-completion-map "C-e" #'gptel-accept-completion)
  (keymap-set gptel-autocomplete-completion-map "<tab>" #'gptel-accept-completion)
  (keymap-set gptel-autocomplete-completion-map "M-f" #'gptel-accept-word)
  (define-key my/ai-map (kbd "<tab>") #'gptel-autocomplete-mode)

  (defun my/gptel-autocomplete-backend (orig &rest args)
    (let ((gptel-backend my/gptel-autocompletion-backend))
      (apply orig args)))
  (advice-add 'gptel-complete :around #'my/gptel-autocomplete-backend))
#+end_src

*** Claude code support

Claude Code can use either Bedrock or Claude API. Set these environment variables
in your shell profile or in =local-pre-init.el=:

**** For Bedrock (work machine):
#+BEGIN_EXAMPLE emacs-lisp
;; In local-pre-init.el:
(setenv "CLAUDE_CODE_USE_BEDROCK" "1")
(setenv "AWS_BEARER_TOKEN_BEDROCK" "your-token")  ; If using bearer token auth
;; Or rely on AWS CLI credentials
#+END_EXAMPLE

**** For Claude API (personal machine):
#+BEGIN_EXAMPLE emacs-lisp
;; In local-pre-init.el:
(setenv "ANTHROPIC_API_KEY" "your-api-key")
;; Leave CLAUDE_CODE_USE_BEDROCK unset or set to ""
#+END_EXAMPLE

**** Vterm terminal emulator

#+begin_src emacs-lisp
(use-package vterm
  :straight t
  :commands (vterm vterm-other-window)
  :init
  ;; Optional: pick a convenient key
  (global-set-key (kbd "C-c t") #'vterm)
  :hook
  ;; Claude Code draws spinners and progress indicators whose width
  ;; fluctuates. Without this Emacs visually wraps long lines onto the
  ;; next row and the TUI jitters constantly.
  (vterm-mode . (lambda () (setq-local truncate-lines t))))
#+end_src

**** Claude Code IDE integration

The =claude-code-ide= package connects Emacs to the Claude Code CLI
via MCP over WebSocket. It provides an ediff-based diff view,
diagnostics forwarding, and Emacs-side tools (xref, imenu, etc.)
that Claude can call.

Focus stays on the ediff buffer when a diff opens so that hunk
navigation (=n= / =p=) works immediately. Use =C-c C-c= to accept
all changes and quit without confirmation prompts, or =C-c C-k= to
cancel and revert the file to its saved state. Both bindings are set
via =ediff-keymap-setup-hook=, which runs after =ediff-set-keys=
creates the keymap (the map is =nil= until then, so earlier hooks
and =with-eval-after-load= do not work).

When Claude edits a file that is already open in Emacs, the diff
handler would normally trigger a "revert buffer?" prompt in the
minibuffer, hiding the diff. A =:before= advice on the diff-buffer
creation function silently reverts the stale buffer so the prompt
never appears. The advice is wrapped in =condition-case= so any
revert failure does not prevent the diff from opening.

#+begin_src emacs-lisp
(use-package claude-code-ide
  :straight (:type git :host github :repo "manzaltu/claude-code-ide.el")
  :bind ("C-q a t" . claude-code-ide-menu)
  :config
  ;; Copy environment variables from shell
  (exec-path-from-shell-copy-env "AWS_BEARER_TOKEN_BEDROCK")
  (exec-path-from-shell-copy-env "CLAUDE_CODE_USE_BEDROCK")
  (exec-path-from-shell-copy-env "ANTHROPIC_API_KEY")
  (setq claude-code-ide-terminal-backend 'vterm)
  (setq claude-code-ide-focus-claude-after-ediff nil)
  (claude-code-ide-emacs-tools-setup)
  ;; Silently revert an already-open buffer before diffing so that
  ;; find-file-noselect does not prompt "revert buffer?" in the
  ;; minibuffer and block the diff view.
  (define-advice claude-code-ide-mcp--create-diff-buffers
      (:before (old-file-path &rest _) auto-revert)
    "Silently revert buffer visiting OLD-FILE-PATH before diffing."
    (condition-case nil
        (when-let ((buf (find-buffer-visiting old-file-path)))
          (with-current-buffer buf
            (revert-buffer t t)))
      (error nil)))
  ;; Accept or cancel ediff without confirmation prompts.
  (add-hook 'ediff-keymap-setup-hook
    (lambda ()
      (define-key ediff-mode-map (kbd "C-c C-c")
        (lambda ()
          (interactive)
          (cl-letf (((symbol-function 'y-or-n-p) (lambda (&rest _) t))
                    ((symbol-function 'yes-or-no-p) (lambda (&rest _) t)))
            (ediff-quit nil))))
      (define-key ediff-mode-map (kbd "C-c C-k")
        (lambda ()
          (interactive)
          (let ((buf ediff-buffer-A))
            (cl-letf (((symbol-function 'y-or-n-p) (lambda (&rest _) t))
                      ((symbol-function 'yes-or-no-p) (lambda (&rest _) t)))
              (ediff-quit nil))
            (when (buffer-live-p buf)
              (with-current-buffer buf
                (revert-buffer t t)))))))))
#+end_src



** Grab environment variables from shell

#+BEGIN_SRC emacs-lisp
(straight-use-package 'exec-path-from-shell)
(require 'exec-path-from-shell)
(exec-path-from-shell-copy-env "AWS_REGION")
(exec-path-from-shell-copy-env "AWS_PROFILE")
#+END_SRC

** Run local init

Finally, after all the other initializations, run local initialization file.
This file (=~/.emacs.d/local-init.el=) should contain:

- Machine-specific package configurations that depend on packages loaded in =init.org=
- Custom functions or keybindings specific to this machine
- Overrides of default settings from =init.org=

*Note:* Use =local-pre-init.el= for configuration that must be set *before* packages
are loaded (like AI backend selection, proxy settings, environment variables).
Use =local-init.el= for configuration that must run *after* packages are loaded.

#+BEGIN_SRC emacs-lisp
  (setq local-init-file "~/.emacs.d/local-init.el")
  (if (file-exists-p local-init-file)
  (load local-init-file)
  )
#+END_SRC

** COMMENT Markdown mode

#+BEGIN_SRC emacs-lisp 
(el-get-install 'markdown-mode)
#+END_SRC
