

#+TITLE: Emacs initialization

* Emacs Initialization
:PROPERTIES:
:header-args: :tangle init.el
:END:

This document describes how Emacs is initialized.
** Run local pre-initialization

Run machine dependant initialization file before running the common
setup. This file (=~/.emacs.d/local-pre-init.el=) should contain configuration
that varies between machines, such as:

- Proxy settings
- AI/LLM backend configuration (Bedrock vs Claude API, Ollama settings)
- Machine-specific environment variables
- Custom paths or hostnames

#+BEGIN_SRC emacs-lisp
  (setq local-pre-init-file "~/.emacs.d/local-pre-init.el")
  (if (file-exists-p local-pre-init-file)
  (load local-pre-init-file)
  )
#+END_SRC

*** Example: Proxy Setup

Following snippet can be used to set up proxy. It tries to ping the
host and if it succeeds within one second, it sets up environment
variables. Package managers will use these when cloning repositories.

#+BEGIN_EXAMPLE emacs-lisp
;; In local-pre-init.el:
(if (= 0 (call-process "ping" nil nil nil "-W" "1" "-c" "1" "1.2.3.4"))
    (progn
      (setenv "http_proxy" "http://1.2.3.4:8080")
      (setenv "https_proxy" "http://1.2.3.4:8080")))
#+END_EXAMPLE

*** Example: AI Backend Configuration

See the "AI tool setup" section below for detailed examples of how to
configure different LLM backends (Bedrock, Claude API, Ollama) in
=local-pre-init.el= for work vs personal machines.

** Straight packet manager

#+BEGIN_SRC emacs-lisp
(defvar bootstrap-version)
(let ((bootstrap-file
       (expand-file-name
        "straight/repos/straight.el/bootstrap.el"
        (or (bound-and-true-p straight-base-dir)
            user-emacs-directory)))
      (bootstrap-version 7))
  (unless (file-exists-p bootstrap-file)
    (with-current-buffer
        (url-retrieve-synchronously
         "https://raw.githubusercontent.com/radian-software/straight.el/develop/install.el"
         'silent 'inhibit-cookies)
      (goto-char (point-max))
      (eval-print-last-sexp)))
  (load bootstrap-file nil 'nomessage))
#+END_SRC

** Appearance
*** All the icons
#+BEGIN_SRC emacs-lisp
  (use-package all-the-icons
  :straight t)
#+END_SRC
*** Minimalistic user interface

Emacs shows startup screen. It gets anoying after a while, so they
need to be turned off.

#+BEGIN_SRC emacs-lisp 
  (setq inhibit-startup-message t)
  (setq inhibit-splash-screen t)
#+END_SRC

After getting used to the keyboard interface the menus and such just
takes valuable screen space. So mouse interface is turned off.
This is done early in the initialization to prevent momentary display.

#+BEGIN_SRC emacs-lisp 
(if (fboundp 'menu-bar-mode) (menu-bar-mode -1))
(if (fboundp 'tool-bar-mode) (tool-bar-mode -1))
(if (fboundp 'scroll-bar-mode) (scroll-bar-mode -1))
#+END_SRC

*** Fonts

Editing a lot of text using fixed width font is not optimum situation. After a while of googling 
I found a way to use variable length fonts (see [[https://yoo2080.wordpress.com/2013/05/30/monospace-font-in-tables-and-source-code-blocks-in-org-mode-proportional-font-in-other-parts/][the blog of Jisan Yoo]]).

First we hook variable-pitch-mode
#+BEGIN_SRC emacs-lisp 
  (add-hook 'text-mode-hook 'variable-pitch-mode)
#+END_SRC

The problem is that I don't want code and tables to be variable width inside
Org mode document. This can be archived by altering some faces
used by the Org mode.

#+BEGIN_SRC emacs-lisp :tangle no
  (defun my-adjoin-to-list-or-symbol (element list-or-symbol)
    (let ((list (if (not (listp list-or-symbol))
                    (list list-or-symbol)
                  list-or-symbol)))
      (require 'cl-lib)
      (cl-adjoin element list)))

    (mapc
      (lambda (face)
        (set-face-attribute
         face nil
         :inherit
         (my-adjoin-to-list-or-symbol
          'fixed-pitch
          (face-attribute face :inherit))))
      (list 'org-code 'org-block 'org-table 'org-meta-line))
#+END_SRC

*** Doom Themes

#+BEGIN_SRC emacs-lisp
  (use-package doom-themes
    :straight t
    :ensure t
    :config
    ;; Global settings (defaults)
    (setq doom-themes-enable-bold t    ; if nil, bold is universally disabled
          doom-themes-enable-italic t) ; if nil, italics is universally disabled
    (load-theme 'doom-acario-dark t)

    ;; Enable flashing mode-line on errors
    (doom-themes-visual-bell-config)
    ;; Enable custom neotree theme (nerd-icons must be installed!)
    (doom-themes-neotree-config)
    ;; or for treemacs users
    (setq doom-themes-treemacs-theme "doom-atom") ; use "doom-colors" for less minimal icon theme
    (doom-themes-treemacs-config)
    ;; Corrects (and improves) org-mode's native fontification.
    (doom-themes-org-config))  
#+END_SRC

#+BEGIN_SRC emacs-lisp
  (use-package doom-modeline
  :ensure t
  :straight t
  :init (doom-modeline-mode 1))
  
 #+END_SRC

 It might be necessary to install fonts (use M-x nerd-icons-install-fonts).

 

  Of course we can choose what kind of faces ~variable-pitch~ and ~fixed-pitch~ are.
 #+BEGIN_SRC emacs-lisp :tangle no
  (set-face-attribute 'variable-pitch nil :height 1.3 :family "FiraCode Nerd Font")
    (set-face-attribute 'variable-pitch nil :height 1.3 :family "Calibri")
    (set-face-attribute 'fixed-pitch nil :height 0.8 :family "DejaVu Sans Mono")
#+END_SRC

While we are at it we could make Org-mode look a little better in general.
#+BEGIN_SRC emacs-lisp :tangle no
(require 'org-bullets)
(add-hook 'org-mode-hook 'org-indent-mode)
(add-hook 'org-mode-hook (lambda () (org-bullets-mode 1)))
(setq org-hide-leading-stars t)
(setq line-spacing 0.25)
(set-face-attribute 'org-tag nil :weight 'normal :height 0.8)
(set-face-attribute 'org-todo nil :weight 'normal :height 150)
(set-face-attribute 'org-priority nil :weight 'normal :height 100)
(set-face-attribute 'org-todo nil :weight 'normal :height 100)
(set-face-attribute 'org-done nil :weight 'normal :height 100)
(set-face-attribute 'org-special-keyword nil :height 90)
(set-face-attribute 'org-level-1 nil :height 1.3)
(set-face-attribute 'org-level-2 nil :height 1.2)
(set-face-attribute 'org-level-3 nil :height 1.1)
#+END_SRC

*** Minibuffer to center of the screen

With wide screen it is a bit complicated to see lower left of the screen. This moves minibuffer to center.

#+BEGIN_SRC emacs-lisp
    (use-package vertico-posframe
      :straight t
      :after vertico
      :init
      (vertico-posframe-mode 1)
      (setq vertico-posframe-poshandler 'posframe-poshandler-frame-top-center)
      )
  #+END_SRC

** Treemacs

#+BEGIN_SRC emacs-lisp
  (use-package treemacs
    :straight t
    :bind
    ("C-x t t" . treemacs)
    :config
    (setq treemacs-width 30)
    (setq treemacs-no-png-images t
        treemacs--icon-size-check nil))
  #+END_SRC

  Needs fronts from https://www.nerdfonts.com/font-downloads
** Docker

#+BEGIN_SRC emacs-lisp
(use-package docker
  :straight t
  :ensure t
  :bind ("C-c d" . docker))
  #+END_SRC
  
** Exec path

At least in MacOS there is problems of ~exec-path~ being insufficient.
The main hedeach this causes is that gpg is not found and encrypted
files can not be opened or saved.

Following code will extract exec-path from ~PATH~ variable.

#+BEGIN_SRC emacs-lisp 
(let ((elements (split-string (getenv "PATH") ":")))
  (dolist (e elements)
    (add-to-list 'exec-path e)))
#+END_SRC

In some cases ~bin~ directory in home directory is missing in the ~exec-path~. Same thing goes to the
~/usr/local/bin~. These are often used in my machines.

#+BEGIN_SRC emacs-lisp 
(add-to-list 'exec-path "~/bin")
(add-to-list 'exec-path "/usr/local/bin")
#+END_SRC

** Lisp files

Additional lisp code is located in own directory. These can be loaded
later using ~require~ function for example.

#+BEGIN_SRC emacs-lisp 
(add-to-list 'load-path "~/.emacs.d/lisp/")
#+END_SRC

** Using GPG-Agent in MacOS

MacOS is a "funny" thing. There is a different environment for shell and
different for applications. This will set the SSH agent socket for Emacs.

#+BEGIN_SRC emacs-lisp 
  (when (eq system-type 'darwin)
  (setenv "SSH_AUTH_SOCK" (concat (getenv "HOME") "/.gnupg/S.gpg-agent.ssh")))
#+END_SRC

** Tabs

Do not indent with tabs by default.

#+BEGIN_SRC emacs-lisp 
(setq-default indent-tabs-mode nil)
#+END_SRC

But if you do use tab its width is two.
#+BEGIN_SRC emacs-lisp 
(setq-default tab-width 2)
#+END_SRC

** No transient mark by default

Following disables [[https://www.emacswiki.org/emacs/TransientMarkMode][transient mark mode]]. This means that text is not selected by
default like in "normal" editors.  This allows more convient text editing while
it requires some practice.

#+BEGIN_SRC emacs-lisp 
(transient-mark-mode 0)
#+END_SRC

** Allow narrowing buffer

After over year of practice I am begin to think that can start to lear some
[[https://www.emacswiki.org/emacs/Narrowing][narrowing]]. It is disabled by default and needs to be enabled.

#+BEGIN_SRC emacs-lisp 
(put 'narrow-to-region 'disabled nil)
#+END_SRC

** Backups

#+BEGIN_SRC emacs-lisp 
(setq backup-directory-alist '(("." . "~/.emacs.d/backups")))
(setq
  delete-old-versions t
  kept-new-versions 6
  kept-old-versions 2
  version-control t
  backup-by-copying t
)
#+END_SRC

** Browser

#+BEGIN_SRC emacs-lisp 
  (when (eq system-type 'darwin)
     (setq browse-url-browser-function 'browse-url-default-macosx-browser))
#+END_SRC

** Org-mode

https://emacs.cafe/emacs/orgmode/gtd/2017/06/30/orgmode-gtd.html

Set up agenda functionality. Files are located under org-directory
under home.

#+BEGIN_SRC emacs-lisp 
(setq org-directory "~/org")
(setq org-agenda-files (concat org-directory "/agenda"))
(setq org-default-notes-file (concat org-directory "/refile.org.gpg"))
#+END_SRC


Set up archive file that is encrypted. By default entries would be archive
to files postfixed by ~_archive~. This file is not encrypted and that could
be a problem.

#+BEGIN_SRC emacs-lisp 
(setq org-archive-location (concat org-directory "/archive.org.gpg::* From %s"))
#+END_SRC


Setup default keys (see [[http://orgmode.org/org.html#Activation][Org mode activation]]). There has not been any
reason to change them yet.
#+BEGIN_SRC emacs-lisp 
  (global-set-key "\C-cl" 'org-store-link)
  (global-set-key "\C-ca" 'org-agenda)
  (global-set-key "\C-cc" 'org-capture)
  (global-set-key "\C-cb" 'org-iswitchb)
#+END_SRC



Active babel languages.
#+BEGIN_SRC emacs-lisp 
(org-babel-do-load-languages
 'org-babel-load-languages
 '(
   (makefile . t)
   (shell . t)
   (js . t)
   (plantuml . t)
   (emacs-lisp  . t)
   (ditaa . t)
   ))
#+END_SRC

*** State changes and logging 

Following will add GTD type of state for the tasks and provide logging.

#+BEGIN_SRC emacs-lisp 
(setq org-log-into-drawer t)
(setq org-todo-keywords '((sequence  "TODO(t!)" "WAIT(w@/!)" "|" "DONE(d!)" "CANCELLED(c@)")))
#+END_SRC

Log looks something like this under the task header line.
#+BEGIN_EXAMPLE
:LOGBOOK:
- State "WAIT"       from "DONE"       [2016-02-22 Mon 16:03]
- State "WAIT"       from "TODO"       [2016-02-22 Mon 16:03]
:END:
#+END_EXAMPLE
apture templates

#+BEGIN_SRC emacs-lisp 
  (setq org-capture-templates
        '(
          ("t" "Task" entry (file "")
            "* TODO %?\n:LOGBOOK:\n- Created %U\n:END:\n%i\n"
           :empty-lines 1)

          ("n" "Note" entry (file "")
           "* %? :muistiinpano:\n:LOGBOOK:\n- Created %U\n:END:\n%i\n"
           :empty-lines 1)

          ("m" "Meeting" entry (file "")
           "* %u %? :tapaminen:\n:LOGBOOK:\n- Created %U\n:END:\n"
           :clock-in t :clock-resume t  :empty-lines 1)

          ("c" "Phone call" entry (file "")
           "* %U %? :puhelu:\n:LOGBOOK:\n- Created %U\n:END:\n"
           :clock-in t :clock-resume t  :empty-lines 1)

          ("j" "Journal" entry (file+datetree "~/org/diary.org.gpg")
           "* %U\n\n%?")

          ("e" "Event" entry (file "")
           "* %? :tapahtuma:\n <%(org-read-date)> \n"
           )))

#+END_SRC


Following enables org-protocol handling. This means that url-like ~org-protocol://capture:/p/<url>/<title>/selection>~
are handled by the org mode capture.

#+begin_src emacs-lisp  
(require 'org-protocol)
#+end_src

Unfinished improvements for GTD.
#+BEGIN_SRC emacs-lisp
      (setq org-agenda-custom-commands
                  '(
                    ("A" "All tasks (for export)" todo ""
                    (
                    (org-agenda-overriding-header "Export")
                    (org-agenda-with-colors nil)
                    ) ("~/org/exported-lists/all.org"))
                    ("Gw" "Agenda työ"
                     (
                       (agenda "" ((org-agenda-span 1)             ; daily agenda
                          (org-deadline-warning-days 7)            ; 7 day advanced warning for deadlines
                          (org-agenda-todo-keyword-format "")
                          (org-agenda-scheduled-leaders '("" ""))
                          (org-agenda-prefix-format "%t%s")))
                      (tags-todo "+työ-@web" ((org-agenda-overriding-header "Työt") (org-agenda-skip-function #'my-org-agenda-skip-all-siblings-but-first)))
                      (tags-todo "+työ+@web" ((org-agenda-overriding-header "Selain") (org-agenda-skip-function #'my-org-agenda-skip-all-siblings-but-first)))
                      (tags-todo "+työ+puhelu" ((org-agenda-overriding-header "Puhelut") (org-agenda-skip-function #'my-org-agenda-skip-all-siblings-but-first)))
                      )
                     (
                     (org-agenda-remove-tags t)
                     (org-agenda-todo-keyword-format "")                  
                     (org-agenda-prefix-format "  %?-12t% s")
                     (org-agenda-compact-blocks t)
                     ))
                    ("Gh" "Agenda koti"
                     (
                       (agenda "" ((org-agenda-span 1)             ; daily agenda
                          (org-deadline-warning-days 7)            ; 7 day advanced warning for deadlines
                          (org-agenda-todo-keyword-format "")
                          (org-agenda-scheduled-leaders '("" ""))
                          (org-agenda-prefix-format "%t%s")))
                      (tags-todo "-työ-@web" ((org-agenda-overriding-header "Työt") (org-agenda-skip-function #'my-org-agenda-skip-all-siblings-but-first)))
                      (tags-todo "-työ+@web" ((org-agenda-overriding-header "Selain") (org-agenda-skip-function #'my-org-agenda-skip-all-siblings-but-first)))
                      (tags-todo "-työ+puhelu" ((org-agenda-overriding-header "Puhelut") (org-agenda-skip-function #'my-org-agenda-skip-all-siblings-but-first)))
                      )
                     (
                     (org-agenda-remove-tags t)
                     (org-agenda-todo-keyword-format "")                  
                     (org-agenda-prefix-format "  %?-12t% s")
                     (org-agenda-compact-blocks t)
                     ))
                    ))


        (defun my-org-agenda-skip-all-siblings-but-first ()
          "Skip all but the first non-done entry."
          (let (should-skip-entry)
            (unless (org-current-is-todo)
              (setq should-skip-entry t))
            (save-excursion
              (while (and (not should-skip-entry) (org-goto-sibling t))
              (when (org-current-is-todo)
                  (setq should-skip-entry t))))
            (when should-skip-entry
              (or (outline-next-heading)
                  (goto-char (point-max))))))

    (defun org-current-is-todo ()
          (string= "TODO" (org-get-todo-state)))

    (defun my-org-scheduled-for-today ()
           (ignore-errors
        (let ((subtree-end (save-excursion (org-end-of-subtree t)))
              (scheduled-day
                (time-to-days
                  (org-time-string-to-time
                    (org-entry-get nil "SCHEDULED"))))
              (now (time-to-days (current-time))))
           (and scheduled-day
                (not (= scheduled-day now))))))

    (defun my-org-agenda-skip-if-not-scheduled-today ()
    "If this function returns nil, the current match should not be skipped.
    Otherwise, the function must return a position from where the search
    should be continued."
    (ignore-errors
        (let ((subtree-end (save-excursion (org-end-of-subtree t)))
              (scheduled-day
                (time-to-days
                  (org-time-string-to-time
                    (org-entry-get nil "SCHEDULED"))))
              (now (time-to-days (current-time))))
           (and scheduled-day
                (not (= scheduled-day now))
                subtree-end))))

    (setq org-refile-targets '(("gtd.org.gpg"  :maxlevel . 1)
                               (org-agenda-files :tag . "prj")
                               ("polar-gtd.org.gpg" :maxlevel . 1)
                               ("someday.org.gpg" :maxlevel . 2)                             
                               ("polar-someday.org.gpg" :maxlevel . 2)))

    (setq org-tags-exclude-from-inheritance '("prj" "puhelu" "muistiinpano" "tapaaminen"))
      (setq org-stuck-projects '("+prj/-MAYBE-DONE-CANCELLED"
                                 ("TODO" "WAIT") ()))

      (defun my-org-with-entry ()
        (interactive)
        (save-excursion
          (org-entry-put nil "with" (read-string "With: " (org-entry-get nil "with")))))
      (global-set-key "\C-cw" 'my-org-with-entry)
#+END_SRC

I have created shell script [[file:sh/orgcapture.sh]] which opens Emacs in capture mode. I have also created service to
MacOS that uses the shell script when keyboard shortcut is used (see [[https://computers.tutsplus.com/tutorials/how-to-launch-any-app-with-a-keyboard-shortcut--mac-31463][instructions]]). Unfortunately Emacs catches all keys
and the same shortcut does not work within Emacs. Following binding enables the same shortcut in
Emacs.

#+BEGIN_SRC emacs-lisp 
  (global-set-key (kbd "C-S-s-o") 'org-capture)
#+END_SRC

** Calendar

See http://orgmode.org/worg/org-faq.html#Appointments/Diary

#+begin_src emacs-lisp 

(setq diary-file "~/org/diary")

(calendar-set-date-style 'european)

(setq calendar-week-start-day 1
      calendar-view-diary-initially-flag t
      calendar-mark-diary-entries-flag t)

(add-hook 'diary-display-hook 'diary-fancy-display)

#+end_src
** Emacsclient server

#+BEGIN_SRC emacs-lisp 
(setq server-socket-dir "~/.emacs.d/server")
(server-start)
#+END_SRC
** New prefix key: Control-q

~Control-q~ is bound to ~quoted-insert~ by default. That command is
not use so often and the key is perfectly located for prefix key.
So it is unset here to allow it to be re-used later.

#+BEGIN_SRC emacs-lisp 
  (global-unset-key (kbd "C-q"))
#+END_SRC

** Vertico, Marginalia, Consult, Orderless

#+BEGIN_SRC emacs-lisp
  (use-package vertico
  :straight t
  :ensure t
  :init
  (vertico-mode))

  (use-package marginalia
  :straight t
  :ensure t
  :init
  (marginalia-mode))

  (use-package consult
  :straight t
  :ensure t
  :bind
  (("C-s" . consult-line)
   ("C-x b" . consult-buffer)
   ("M-y" . consult-yank-pop)))

  (use-package orderless
  :straight t
  :init
  (setq completion-styles '(orderless)))
#+END_SRC

** Misc


#+BEGIN_SRC emacs-lisp 
  ;;; turn on syntax highlighting
  (global-font-lock-mode 1)

  ;; Mustache mode
  (require 'mustache-mode)

  (defun iwb ()
    "indent whole buffer"
    (interactive)
    (delete-trailing-whitespace)
    (indent-region (point-min) (point-max) nil)
    (untabify (point-min) (point-max)))

  (defun previous-line-insert-newline ()
    "Moves line up and creates empty line"
    (interactive)
    (previous-line)
    (end-of-line)
    (newline-and-indent)
    )

  (defun next-line-insert-newline ()
    "Moves line up and creates empty line"
    (interactive)
    (end-of-line)
    (newline-and-indent)
    )

  (setq line-move-visual nil)
  (put 'scroll-left 'disabled nil)

  ;; (global-set-key (kbd "C-,") 'backward-paragraph)
  ;; (global-set-key (kbd "C-.") 'forward-paragraph)
  ;; (global-set-key  (kbd "C-`")    'shell-command)
  ;; (global-set-key  (kbd "M-`")    'shell-command-on-region)


  (global-set-key (kbd "C-c f") 'iwb)

  ;; Moving from window to window using arrows
  (global-set-key (kbd "<left>")  'windmove-left)
  (global-set-key (kbd "<right>") 'windmove-right)
  (global-set-key (kbd "<up>")    'windmove-up)
  (global-set-key (kbd "<down>")  'windmove-down)

  (global-set-key (kbd "M-n") 'next-line-insert-newline)
  (global-set-key (kbd "M-p") 'previous-line-insert-newline)



  (global-unset-key (kbd "C-<SPC>"))
  (global-set-key (kbd "C-<SPC>") 'set-mark-command)



  (global-set-key (kbd "s-<left>")  'windmove-left)
  (global-set-key (kbd "s-<right>") 'windmove-right)
  (global-set-key (kbd "s-<up>")    'windmove-up)
  (global-set-key (kbd "s-<down>")  'windmove-down)

  (put 'upcase-region 'disabled nil)
  (put 'scroll-left 'disabled nil)

  (global-set-key (kbd "C-q o")  'find-file-at-point)

  (global-set-key (kbd "C-q i")  'quoted-insert)
#+END_SRC

** Shell stuff 
*** Convient way to create new shell

I often need shell. But default ~M-x shell~ will throw back to the already
created shell. Many times this is not what I want.

#+begin_src emacs-lisp 
    (defun ps/open-new-shell ()
      (interactive)

      (let (
            (currentbuf (get-buffer-window (current-buffer)))
            (newbuf     (generate-new-buffer-name "*shell*"))
           )
       (generate-new-buffer newbuf)
       (set-window-dedicated-p currentbuf nil)
       (set-window-buffer currentbuf newbuf)
       (shell newbuf)
      )
    )
  (defun ps/open-new-local-shell ()
    "Open a new shell buffer in home directory."
    (interactive)
    (let ((default-directory "~/"))
          (ps/open-new-shell)))

  (global-set-key (kbd "C-q s")  'ps/open-new-shell)
  (global-set-key (kbd "C-q C-s")  'ps/open-new-local-shell)
#+end_src

*** Jumping to the root directory of repository

Sometimes it is convenient to jump to the root directory of the repository.

#+begin_src emacs-lisp 
(defun pw/shell-cd-to-vc-root ()
"Jumps to the root directory of version controled directory structure."
  (interactive)
  (let* ((proc (get-buffer-process (current-buffer)))
         (pmark (process-mark proc))
	 (started-at-pmark (= (point) (marker-position pmark)))         
         (root (vc-root-dir))
         (cmd (concat "cd " root)))
    (save-excursion
      (goto-char pmark)
      (unless comint-process-echoes     
         (insert cmd) (insert "\n"))
      (sit-for 0)			; force redisplay      
      (cd root)
      (comint-send-string proc cmd)
      (comint-send-string proc "\n")
      (set-marker pmark (point))
      )
    
    (if started-at-pmark (goto-char (marker-position pmark)))))

(defun pw/dired-cd-to-vc-root ()
(interactive)
(find-file (vc-root-dir)))

#+end_src

This function can be binded to key sequence when shell is activated.
#+begin_src emacs-lisp 
  (add-hook 'comint-mode-hook (lambda ()
                              (define-key comint-mode-map (kbd "C-q c r") 'pw/shell-cd-to-vc-root)
                              ))

  (add-hook 'dired-mode-hook (lambda ()
                              (define-key dired-mode-map (kbd "C-q c r") 'pw/dired-cd-to-vc-root)
                              ))

#+end_src
*** No passwords in shell

#+BEGIN_SRC emacs-lisp 
;; No passwords show in shell
(add-hook 'comint-output-filter-functions
          'comint-watch-for-password-prompt)
#+END_SRC

** Avy - for jumping around

#+BEGIN_SRC emacs-lisp
      (use-package avy
       :straight t
       :bind (
              ("C-." . avy-goto-char)
              ("C-q q". avy-pop-mark)))
#+END_SRC

#+BEGIN_SRC emacs-lisp :tangle no
  ;; 
  ;; enable a more powerful jump back function from ace jump mode
  ;;
  (autoload
    'ace-jump-mode-pop-mark
    "ace-jump-mode"
    "Ace jump back:-)"
    t)
  (eval-after-load "ace-jump-mode"
    '(ace-jump-mode-enable-mark-sync))
  (define-key global-map (kbd "C-q q") 'ace-jump-mode-pop-mark)
  (define-key global-map (kbd "C-.") 'ace-jump-mode)
#+END_SRC
** COMMENT File editing modes
*** COMMENT CSV-mode
#+BEGIN_SRC emacs-lisp 
;; CSV Mode
(el-get-bundle csv-mode)
(require 'csv-mode)
#+END_SRC
*** COMMENT Docker-mode
#+BEGIN_SRC emacs-lisp 
(el-get-bundle dockerfile-mode)
;;; Dockerfile mode
(require 'dockerfile-mode)
(add-to-list 'auto-mode-alist '("Dockerfile\\'" . dockerfile-mode))
#+END_SRC
*** Yaml-mode
#+BEGIN_SRC emacs-lisp 
(el-get-bundle yaml-mode)
#+END_SRC
** COMMENT Edit server

Edit server allows editing content from web browser. See for example [[https://chrome.google.com/webstore/detail/edit-with-emacs/ljobjlafonikaiipfkggjbhkghgicgoh][edit-with-emacs]] Chrome extension.

This is disabled as there seems to be some kind of load problem at the moment [2020-04-14].

#+BEGIN_SRC emacs-lisp :tangle no
(el-get-bundle edit-server)
(edit-server-start)
#+END_SRC

** COMMENT Expand region
#+BEGIN_SRC emacs-lisp 
(el-get-bundle expand-region)
(require 'expand-region)
(global-set-key (kbd "C-q C-e") 'er/expand-region)
#+END_SRC
** COMMENT Setup Go environment


#+BEGIN_SRC emacs-lisp 
(defun system-has-go () "Tests wether go is installed or not" 
       (condition-case nil
           (progn
             (start-process "" nil "go")
             t
             )
         (error nil))
       )
(defun makeinfo-version () "Make info version"
       (with-temp-buffer
          (call-process "makeinfo" nil t nil "--version")
          (goto-char (point-min))
          (re-search-forward "[0-9]\\{1,2\\}\\(\\.[0-9]\\{1,2\\}\\)\\{1,2\\}")
          (let ((s (match-beginning 0)) (e (point)))
            (mapcar
             'string-to-number
             (split-string (buffer-substring s e) "\\.")))))

(defun setup-go () "Install go environment with el-get"
       (el-get-bundle go-mode)
       (el-get-bundle dash)
       
       ;; Require makeinfo which major version is 5 or more
       (if (< 4 (car (makeinfo-version)))
           (progn
           (el-get-bundle flycheck)   
           ;; go get github.com/dougm/goflymake
           (add-to-list 'load-path "~/src/github.com/dougm/goflymake")
           (require 'go-flycheck))
           ))

       ;; go get github.com/nsf/gocode
       (el-get-bundle go-autocomplete)
       (require 'go-autocomplete)

       (add-hook 'go-mode-hook 
                 (lambda ()
                   (define-key go-mode-map (kbd "C-q j") 'godef-jump)
                   (define-key go-mode-map (kbd "C-q q") 'pop-global-mark)
                   (add-hook 'before-save-hook 'gofmt-before-save))
                 )

(if (system-has-go) (setup-go))
#+END_SRC

** COMMENT Multicursors
#+BEGIN_SRC emacs-lisp 
(el-get-bundle multiple-cursors)

(global-set-key (kbd "C-c m <return>") 'set-rectangular-region-anchor)
(global-set-key (kbd "C-c m c") 'mc/edit-lines)
(global-set-key (kbd "C-c m a") 'mc/mark-all-like-this)
(global-set-key (kbd "C-c m .") 'mc/mark-next-like-this)
(global-set-key (kbd "C-c m ,") 'mc/mark-previous-like-this)
(global-set-key (kbd "C-c m m") 'mc/mark-more-like-this-extended)
#+END_SRC

** COMMENT Yasniplet and autocomplete
#+BEGIN_SRC emacs-lisp 
(el-get-bundle yasnippet)
(el-get-bundle auto-complete)


(require 'yasnippet)
(require 'auto-complete)
(require 'auto-complete-config)
;;(require 'auto-complete-yasnippet)

(ac-config-default)
;(global-set-key (kbd "C-<tab>")  'yas-expand)

(setq ac-source-yasnippet nil)

;;; auto complete mod
;;; should be loaded after yasnippet so that they can work together

(add-to-list 'ac-dictionary-directories "~/.emacs.d/ac-dict")

;;; set the trigger key so that it can work together with yasnippet on tab key,
;;; if the word exists in yasnippet, pressing tab will cause yasnippet to
;;; activate, otherwise, auto-complete will
(ac-set-trigger-key "<tab>")



;; (setq-default ac-sources
;;       '(
;;         ;; ac-source-semantic
;;         ac-source-yasnippet
;;         ac-source-abbrev
;;         ac-source-words-in-buffer
;;         ac-source-words-in-all-buffer
;;         ;; ac-source-imenu
;;         ac-source-files-in-current-dir
;;         ac-source-filename
;;         )
;;       )

(yas-global-mode 1)
(global-auto-complete-mode 1)

#+END_SRC
** Buffer switching

One common task is to switch between two buffers.
Suspend frame is not very usefull command so, it is
recycled to change the buffer.

#+begin_src emacs-lisp 
(global-set-key (kbd "C-z")  'mode-line-other-buffer)
#+end_src

** IBuffers

#+begin_src emacs-lisp 
   (global-set-key (kbd "C-x C-b") 'ibuffer)
   (autoload 'ibuffer "ibuffer" "List buffers." t)

    (setq ibuffer-saved-filter-groups
            (quote (("default"
                     ("dired" (mode . dired-mode))
                     ("org" (or
                             (mode . org-mode)
                             (mode . org-agenda-mode)                           
                             ))
                     ("emacs" (or
                               (name . "^\\*scratch\\*$")
                               (name . "^\\*Messages\\*$")))
                     ("shell" (or
                              (mode . shell-mode)
                              (mode . term-mode)
                              ))))))

#+end_src

** COMMENT WCheck mode

Set up wcheck mode for spell checking

#+BEGIN_SRC emacs-lisp
  (el-get-bundle 'wcheck-mode)
  (global-set-key (kbd "C-x w") 'wcheck-mode)
  (add-hook 'wcheck-mode-hook
            (lambda ()
              (define-key wcheck-mode-map (kbd "C-q l") 'wcheck-change-language)
              (define-key wcheck-mode-map (kbd "C-q c") 'wcheck-actions)
              (define-key wcheck-mode-map (kbd "C-q n") 'wcheck-jump-forward)
              (define-key wcheck-mode-map (kbd "C-q p") 'wcheck-jump-backward)
              ))

  (setq wcheck-language-data
        '(
          ("British English"
           (program . "/usr/bin/enchant")
           (args "-l" "-d" "british")
           (action-program . "/usr/bin/ispell")
           (action-args "-a" "-d" "british")
           (action-parser . wcheck-parser-ispell-suggestions))

          ("Finnish"
           (program . "/usr/bin/enchant")
           (args "-l" "-d" "fi")
           (action-program . "/usr/bin/enchant")
           (action-args "-a" "-d" "fi")
           (action-parser . wcheck-parser-ispell-suggestions))

          ))

  (wcheck-change-language "British English" 'GLOBAL)

#+END_SRC

** Magit for using git

#+BEGIN_SRC emacs-lisp
  (use-package magit
    :straight t
    :bind ("C-x g" . magit-status))

  (use-package treemacs-magit  :straight t :after (treemacs magit))
#+END_SRC

** COMMENT Kill buffer instead of burying it

#+begin_src emacs-lisp 
(defadvice quit-window (before quit-window-always-kill)
  "When running `quit-window', always kill the buffer."
  (ad-set-arg 0 t))
(ad-activate 'quit-window)
#+end_src
** Default column width 80 characters
#+begin_src emacs-lisp 
(setq default-fill-column 80)
#+end_src

** Don't confirm kills

#+BEGIN_SRC emacs-lisp

  (global-set-key (kbd "C-x k")
                (lambda () (interactive) (kill-this-buffer)))
#+END_SRC

** Protocol Buffers  mode

[[https://developers.google.com/protocol-buffers/docs/overview][Google Protocol Buffers]] is way to serialize data. It uses "proto" files to describe serialization format.

#+begin_src emacs-lisp 
(require 'protobuf-mode)
(add-to-list 'auto-mode-alist '("\\.proto\\'" . protobuf-mode))
#+end_src

** Open current buffer in idea
#+begin_src emacs-lisp 
  (defun open-buffer-curent-idea ()
    ""
    (interactive)
    (call-process "idea" nil nil nil (buffer-file-name))
    (if (string-equal system-type "darwin")
        (ns-do-applescript "tell application \"IntelliJ Idea\" to activate")
      )
  )

  (global-set-key (kbd "C-q C-o")  'open-buffer-curent-idea)
#+end_src

** Toggle transparency of current frame

Sometime it is nice to look what is behind the frame. Following code toggles frame to be almost completely transparent
and back to solid again. 
#+begin_src emacs-lisp 
  (defun ps/toggle-transparency ()
    "Toggles frame transparency."
    (interactive)
    (if (equal '(100 100) (frame-parameter (selected-frame) 'alpha))
        (set-frame-parameter (selected-frame) 'alpha '(10 10))
      (set-frame-parameter (selected-frame) 'alpha '(100 100))))

  (global-set-key (kbd "C-q t")  'ps/toggle-transparency)
#+end_src

** PlantUML support

PlantUML works using JAR. Next is function that will load the jar if it is missing. Function returns the path where the
jar was loaded.

#+begin_src emacs-lisp 
  (defun pw/download-plantuml-jar-if-needed () ""
         (let ((plantuml-jar "~/.emacs.d/plantuml.jar"))
           (if (not (file-exists-p plantuml-jar))
               (progn
                 (url-copy-file "http://downloads.sourceforge.net/project/plantuml/plantuml.jar?r=http%3A%2F%2Fplantuml.com%2Fdownload.html&ts=1441279540&use_mirror=netix" plantuml-jar)
                 ))
           (expand-file-name plantuml-jar)))
#+end_src

#+begin_src emacs-lisp
  (use-package deflate
    :straight (deflate :type git :host github :repo "skuro/deflate"))

    (use-package plantuml-mode
      :straight (plantuml-mode :type git :host github :repo "skuro/plantuml-mode")
      :mode ("\\.plantuml\\'" "\\.puml\\'")
      :config
      (setq plantuml-default-exec-mode 'jar
            org-plantuml-jar-path (pw/download-plantuml-jar-if-needed)
            plantuml-jar-path (pw/download-plantuml-jar-if-needed)))
#+end_src

Now we can set the PlantUML jar for org-mode.
#+begin_src emacs-lisp 
;; Don`t confirm plant uml runs for conviency.
(let ((default-confirm org-confirm-babel-evaluate))
  (defun my-org-confirm-babel-evaluate (lang body)
    (if (string= lang "plantuml") nil default-confirm))
  (setq org-confirm-babel-evaluate 'my-org-confirm-babel-evaluate)
  )

(add-hook 'org-babel-after-execute-hook 'org-display-inline-images)
(setq org-startup-with-inline-images t)
(setq plantuml-indent-level 2)
(setq org-src-tab-acts-natively t)
(setq org-edit-src-content-indentation 0)
#+end_src
** AI tool setup

This section configures AI tools (gptel, ellama, aidermacs, Claude Code) for use with
different LLM backends. The configuration is designed to be machine-independent by using
variables that can be overridden in =local-pre-init.el=.

*** Machine-Dependent Configuration

The following variables control which LLM backend is used and should be set in
=~/.emacs.d/local-pre-init.el= before this configuration loads:

**** Work Machine Example (Bedrock + Ollama)
#+BEGIN_EXAMPLE emacs-lisp
;; In local-pre-init.el for work machine:
;; Use AWS Bedrock for main chat, Ollama for autocomplete

;; Ollama configuration (for autocomplete)
(defvar my/ollama-host-name "127.0.0.1")
(defvar my/ollama-port 11434)
(defvar my/ollama-chat-model "gpt-oss:20b")
(defvar my/ollama-fast-model "llama3.1:8b")
(defvar my/ollama-utility-model "qwen2.5-coder:14b")
(defvar my/ollama-embedding-model "nomic-embed-text")

;; Use Bedrock for gptel
(defvar my/use-bedrock-gptel t)
(defvar my/bedrock-region "eu-west-1")
(defvar my/bedrock-model-region 'eu)
(defvar my/bedrock-model 'claude-opus-4-6)

;; Use Ollama for autocomplete
(defvar my/use-ollama-autocomplete t)
#+END_EXAMPLE

**** Personal Machine Example (Claude API + Ollama)
#+BEGIN_EXAMPLE emacs-lisp
;; In local-pre-init.el for personal machine:
;; Use Claude API directly, Ollama for autocomplete

;; Ollama configuration (for autocomplete and ellama)
(defvar my/ollama-host-name "127.0.0.1")
(defvar my/ollama-port 11434)
(defvar my/ollama-chat-model "gpt-oss:20b")
(defvar my/ollama-fast-model "llama3.1:8b")
(defvar my/ollama-utility-model "qwen2.5-coder:14b")
(defvar my/ollama-embedding-model "nomic-embed-text")

;; Use Claude API for gptel
(defvar my/use-bedrock-gptel nil)
(defvar my/claude-api-key "your-api-key-here")  ; Or use auth-source
(defvar my/claude-model 'claude-sonnet-4-20250514)

;; Use Ollama for autocomplete
(defvar my/use-ollama-autocomplete t)
#+END_EXAMPLE

*** Default Values (used if not set in local-pre-init.el)

#+begin_src emacs-lisp
;; Ollama host configuration
(unless (boundp 'my/ollama-host-name)
  (defvar my/ollama-host-name "127.0.0.1"))
(unless (boundp 'my/ollama-port)
  (defvar my/ollama-port 11434))

;; Ollama model names
(unless (boundp 'my/ollama-chat-model)
  (defvar my/ollama-chat-model "gpt-oss:20b"))
(unless (boundp 'my/ollama-fast-model)
  (defvar my/ollama-fast-model "llama3.1:8b"))
(unless (boundp 'my/ollama-utility-model)
  (defvar my/ollama-utility-model "qwen2.5-coder:14b"))
(unless (boundp 'my/ollama-embedding-model)
  (defvar my/ollama-embedding-model "nomic-embed-text"))

;; Derived variable
(defvar my/ollama-host
  (format "%s:%d" my/ollama-host-name my/ollama-port))

;; Backend selection defaults
(unless (boundp 'my/use-bedrock-gptel)
  (defvar my/use-bedrock-gptel t))  ; Default to Bedrock
(unless (boundp 'my/use-ollama-autocomplete)
  (defvar my/use-ollama-autocomplete t))

;; Bedrock configuration defaults
(unless (boundp 'my/bedrock-region)
  (defvar my/bedrock-region "us-east-1"))
(unless (boundp 'my/bedrock-model-region)
  (defvar my/bedrock-model-region 'us))
(unless (boundp 'my/bedrock-model)
  (defvar my/bedrock-model 'claude-sonnet-4-20250514))

;; Claude API configuration defaults
(unless (boundp 'my/claude-api-key)
  (defvar my/claude-api-key nil))  ; Should be set in local-pre-init.el
(unless (boundp 'my/claude-model)
  (defvar my/claude-model 'claude-sonnet-4-20250514))
#+end_src

*** AI keymap
#+begin_src emacs-lisp
(define-prefix-command 'my/ai-map)
(global-set-key (kbd "C-q a") #'my/ai-map)
#+end_src

*** gptel

Configure gptel to use either Bedrock or Claude API based on machine configuration.

#+begin_src emacs-lisp
(use-package gptel
  :ensure t
  :commands (gptel gptel-send gptel-rewrite)
  :init
  ;; Always set up Ollama backend (might be used for autocomplete)
  (setq my/gptel-ollama
        (gptel-make-ollama
         "Ollama"
         :host my/ollama-host
         :stream t
         :models (mapcar #'intern
                        (list my/ollama-chat-model
                              my/ollama-fast-model
                              my/ollama-utility-model))))

  ;; Set up the main backend based on configuration
  (if my/use-bedrock-gptel
      ;; Use AWS Bedrock
      (progn
        (setq my/gptel-main-backend
              (gptel-make-bedrock
               "Claude-Bedrock"
               :stream t
               :region 'eu-west-1'
               :model-region 'eu
               :models '(claude-opus-4-6
                 claude-sonnet-4-20250514
                 claude-haiku-4-5-20251001)))               

        (setq my/gptel-main-model my/bedrock-model))
    ;; Use Claude API directly
    (progn
      (setq my/gptel-main-backend
            (gptel-make-anthropic
             "Claude"
             :stream t
             :key my/claude-api-key))  ; Can also use 'gptel-api-key for auth-source
      (setq my/gptel-main-model my/claude-model)))

  :config
  (setq gptel-backend my/gptel-main-backend)
  (setq gptel-model my/gptel-main-model)
  (setq gptel-default-mode 'org-mode)
  (setq gptel-track-response nil)

  (define-key my/ai-map (kbd "c") #'gptel)
  (define-key my/ai-map (kbd "s") #'gptel-send)
  (define-key my/ai-map (kbd "r") #'gptel-rewrite))
#+end_src

*** aidermacs

Aider configuration uses environment variables =AIDER_MODEL= and =AIDER_WEAK_MODEL=.
These should be set in your shell profile or in =local-pre-init.el= using:

#+BEGIN_EXAMPLE emacs-lisp
;; In local-pre-init.el (optional, if not set in shell):
(setenv "AIDER_MODEL" "bedrock/anthropic.claude-sonnet-4-20250514-v1:0")
(setenv "AIDER_WEAK_MODEL" "bedrock/anthropic.claude-3-5-haiku-20241022-v1:0")
;; or for personal machine:
(setenv "AIDER_MODEL" "claude-sonnet-4-20250514")
(setenv "AIDER_WEAK_MODEL" "claude-3-5-haiku-20241022")
#+END_EXAMPLE

#+begin_src emacs-lisp
(use-package aidermacs
  :ensure t
  :commands (aidermacs-transient-menu aidermacs-run-aider)
  :init
  (setq aidermacs-default-chat-mode 'architect)
  (setq aidermacs-use-voice nil)
  :config
  (setq aidermacs-default-model (exec-path-from-shell-getenv "AIDER_MODEL"))
  (setq aidermacs-weak-model (exec-path-from-shell-getenv "AIDER_WEAK_MODEL"))
  (define-key my/ai-map (kbd "a") #'aidermacs-transient-menu))
#+end_src

*** aidermacs / git helper
#+begin_src emacs-lisp
(defun my/git-diff-staged-to-buffer ()
  "Show staged git diff in a temp buffer."
  (interactive)
  (let ((buf (get-buffer-create "*git-staged-diff*")))
    (with-current-buffer buf
      (erase-buffer)
      (call-process "git" nil buf nil "diff" "--staged")
      (diff-mode))
    (pop-to-buffer buf)))

(define-key my/ai-map (kbd "d") #'my/git-diff-staged-to-buffer)
#+end_src

*** ellama
#+begin_src emacs-lisp
(use-package llm
  :ensure t)

(use-package ellama
  :ensure t
  :after llm
  :config
  (require 'llm-ollama)

  (setq ellama-provider
        (make-llm-ollama
         :host my/ollama-host-name
         :port my/ollama-port
         :chat-model my/ollama-utility-model
         :embedding-model my/ollama-embedding-model))


  (setq ellama-language "English")
  (setq ellama-naming-provider ellama-provider)
  (setq ellama-summarization-provider ellama-provider)

  (define-key my/ai-map (kbd "e") #'ellama)
  (define-key my/ai-map (kbd "i") #'ellama-improve-wording)
  (define-key my/ai-map (kbd "m") #'ellama-summarize))
#+end_src

*** gptel autocomplete

Autocomplete can use either Ollama (faster, local) or the main backend.
Set =my/use-ollama-autocomplete= in =local-pre-init.el= to control this.

#+begin_src emacs-lisp
;; Set up autocomplete backend based on configuration
(when my/use-ollama-autocomplete
  (setq my/gptel-autocompletion-backend
        (gptel-make-ollama
         "autocomplete"
         :host my/ollama-host
         :models (list my/ollama-utility-model))))

;; If not using Ollama, use the main backend
(unless (boundp 'my/gptel-autocompletion-backend)
  (setq my/gptel-autocompletion-backend my/gptel-main-backend))

(use-package gptel-autocomplete
  :straight '(:type git :host github :repo "JDNdeveloper/gptel-autocomplete")
  :config
  (require 'gptel-autocomplete)
  (setq gptel-autocomplete-before-context-lines 100
        gptel-autocomplete-after-context-lines 20
        gptel-autocomplete-temperature 0.1
        gptel-autocomplete-use-context t
        gptel-autocomplete-idle-delay 0)
  (keymap-set gptel-autocomplete-completion-map "C-e" #'gptel-accept-completion)
  (keymap-set gptel-autocomplete-completion-map "<tab>" #'gptel-accept-completion)
  (keymap-set gptel-autocomplete-completion-map "M-f" #'gptel-accept-word)
  (define-key my/ai-map (kbd "<tab>") #'gptel-autocomplete-mode)

  (defun my/gptel-autocomplete-backend (orig &rest args)
    (let ((gptel-backend my/gptel-autocompletion-backend))
      (apply orig args)))
  (advice-add 'gptel-complete :around #'my/gptel-autocomplete-backend))
#+end_src

*** Claude code support

Claude Code can use either Bedrock or Claude API. Set these environment variables
in your shell profile or in =local-pre-init.el=:

**** For Bedrock (work machine):
#+BEGIN_EXAMPLE emacs-lisp
;; In local-pre-init.el:
(setenv "CLAUDE_CODE_USE_BEDROCK" "1")
(setenv "AWS_BEARER_TOKEN_BEDROCK" "your-token")  ; If using bearer token auth
;; Or rely on AWS CLI credentials
#+END_EXAMPLE

**** For Claude API (personal machine):
#+BEGIN_EXAMPLE emacs-lisp
;; In local-pre-init.el:
(setenv "ANTHROPIC_API_KEY" "your-api-key")
;; Leave CLAUDE_CODE_USE_BEDROCK unset or set to ""
#+END_EXAMPLE

**** Vterm terminal emulator

#+begin_src elisp
(use-package vterm
  :straight t
  :commands (vterm vterm-other-window)
  :init
  ;; Optional: pick a convenient key
  (global-set-key (kbd "C-c t") #'vterm))
#+end_src

#+begin_src emacs-lisp
(use-package claude-code-ide
  :straight (:type git :host github :repo "manzaltu/claude-code-ide.el")
  :bind ("C-q a t" . claude-code-ide-menu)
  :config
  ;; Copy environment variables from shell
  (exec-path-from-shell-copy-env "AWS_BEARER_TOKEN_BEDROCK")
  (exec-path-from-shell-copy-env "CLAUDE_CODE_USE_BEDROCK")
  (exec-path-from-shell-copy-env "ANTHROPIC_API_KEY")
  (setq claude-code-ide-terminal-backend 'vterm)
  (claude-code-ide-emacs-tools-setup))
#+end_src



** Grab environment variables from shell

#+BEGIN_SRC emacs-lisp
(straight-use-package 'exec-path-from-shell)
(require 'exec-path-from-shell)
(exec-path-from-shell-copy-env "AWS_REGION")
(exec-path-from-shell-copy-env "AWS_PROFILE")
#+END_SRC

** Run local init

Finally, after all the other initializations, run local initialization file.
This file (=~/.emacs.d/local-init.el=) should contain:

- Machine-specific package configurations that depend on packages loaded in =init.org=
- Custom functions or keybindings specific to this machine
- Overrides of default settings from =init.org=

*Note:* Use =local-pre-init.el= for configuration that must be set *before* packages
are loaded (like AI backend selection, proxy settings, environment variables).
Use =local-init.el= for configuration that must run *after* packages are loaded.

#+BEGIN_SRC emacs-lisp
  (setq local-init-file "~/.emacs.d/local-init.el")
  (if (file-exists-p local-init-file)
  (load local-init-file)
  )
#+END_SRC

** COMMENT Markdown mode

#+BEGIN_SRC emacs-lisp 
(el-get-install 'markdown-mode)
#+END_SRC
